$axure.loadCurrentPage({
  "url":"问题发布页.html",
  "generationDate":new Date(1491295964308.47),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"40816cc30f704796b9e4105ebadcd4c3",
    "type":"Axure:Page",
    "name":"问题发布页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"dace685a1fdc4a9f81dfc5b8a819a22b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "size":{
              "width":1200,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b9d749187d647aa96569ebc13ac3ed0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "size":{
                  "width":1200,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u0.png"}},
{
          "id":"ae06f51d46b042a0a68c6376cd7f40c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":27,
              "y":0},
            "size":{
              "width":202,
              "height":118}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b31e4cdb2574bfab0ce8a038bc7cb4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":27,
                  "y":0},
                "size":{
                  "width":202,
                  "height":118}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登陆后",
                      "target":{
                        "targetType":"page",
                        "url":"登陆后.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"43a9083ee36c49a1b62b6ab0f0263ad6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1051,
              "y":20},
            "size":{
              "width":80,
              "height":80},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"100"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9f033a5ed5d45ee89257b86b37637cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1051,
                  "y":20},
                "size":{
                  "width":80,
                  "height":80},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"100"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u4.png"}},
{
          "id":"28900071ccbb4ed0b9e162cfa9b5e4f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":0,
              "y":130},
            "size":{
              "width":230,
              "height":890}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a105f5439814b5eb88223fef1e146fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":0,
                  "y":130},
                "size":{
                  "width":230,
                  "height":890}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发布公告页/u6.png"}},
{
          "id":"87c89a402aca4c94ae622ac574b5a488",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":213},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee42fe2748f3427fb47dfbb5f52a7b62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":213},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登陆后",
                      "target":{
                        "targetType":"page",
                        "url":"登陆后.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ba4188170d0c4568b1a319217c820a72",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":308},
            "size":{
              "width":97,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"417dbb67d92646a787124ada4dbf44d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":308},
                "size":{
                  "width":97,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 公告栏主页面",
                      "target":{
                        "targetType":"page",
                        "url":"公告栏主页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"19e247deafcb4ba5b498cb15c0df2c63",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":400},
            "size":{
              "width":97,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2028eecb1e44f7b84273317d91fc020",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":400},
                "size":{
                  "width":97,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 讨论区主页面",
                      "target":{
                        "targetType":"page",
                        "url":"讨论区主页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d43ab6da874d4c138da951e5db524b53",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":490},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98320176397348e2a6a6fcd86cd22083",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":490},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 成绩管理主页面",
                      "target":{
                        "targetType":"page",
                        "url":"成绩管理主页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"31c92e0f00484723994e7baf0570366d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF363636},
            "location":{
              "x":0,
              "y":1020},
            "size":{
              "width":1200,
              "height":180}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d84eea71bc2e46cea2053bd4c5e329c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF363636},
                "location":{
                  "x":0,
                  "y":1020},
                "size":{
                  "width":1200,
                  "height":180}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u18.png"}},
{
          "id":"683b0d5afbed47d490fd2b266c54ff26",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":59,
              "y":1045},
            "size":{
              "width":87,
              "height":85}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd0900b0562c41b6926c338f1a9406c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":59,
                  "y":1045},
                "size":{
                  "width":87,
                  "height":85}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u20.jpg"}},
{
          "id":"03604c1325af410597a935df84e0c765",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'方正舒体 Regular', '方正舒体'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":45,
              "y":1140},
            "size":{
              "width":126,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a14988436b24cddb2c161fda613462a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'方正舒体 Regular', '方正舒体'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":45,
                  "y":1140},
                "size":{
                  "width":126,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b7f05b32b4db4fefad898c2fd2e7e4ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":600,
              "y":1045},
            "size":{
              "width":117,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee4b7dc3a36a446395680ba2b7e9be16",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":600,
                  "y":1045},
                "size":{
                  "width":117,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f73ce96138de4f06bf9dc6b3e2387b0e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":600,
              "y":1102},
            "size":{
              "width":77,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29dfb9acddfb41818cb04efdb411c5d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":600,
                  "y":1102},
                "size":{
                  "width":77,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9b6970b4d0c84399926eaf130c7e89d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":693,
              "y":1102},
            "size":{
              "width":77,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1db092431a9d4725bdc47062664204c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":693,
                  "y":1102},
                "size":{
                  "width":77,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7c259ec7ca454fc5b534c31296b325be",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":600,
              "y":1141},
            "size":{
              "width":77,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"765c5dc0965a4fa28f1b63c2d33b5650",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":600,
                  "y":1141},
                "size":{
                  "width":77,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7507b50f199b4e968cb3793c910b65f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":691,
              "y":1141},
            "size":{
              "width":77,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"269193dd2f024777af043bdc67e51ee0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":691,
                  "y":1141},
                "size":{
                  "width":77,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"42462e330ab14995a9299fd6673e05b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":920,
              "y":1045},
            "size":{
              "width":117,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e4c1da4b18a4436a02ac9670d2e7ea8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":920,
                  "y":1045},
                "size":{
                  "width":117,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2c93728ce25c4c3f93735c812d3ecbe5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":920,
              "y":1102},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb48ff5467b740a486e5e88817bb29c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":920,
                  "y":1102},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u36.png"}},
{
          "id":"2fd7c89b44ed4f30b3ce0810e45bb9d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1000,
              "y":1102},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d8d6707971f4211a15d45d69e5d4644",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1000,
                  "y":1102},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u36.png"}},
{
          "id":"83716c3f19ac433cb22f81b93a0b9de7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":1134,
              "y":55},
            "size":{
              "width":24,
              "height":18},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cdc949bd3e5647a1ae9810ce1ff74d37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":1134,
                  "y":55},
                "size":{
                  "width":24,
                  "height":18},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"切换 set",
                      "objectsToFades":[{
                          "objectPath":["42d9a8efb6124ad185e52e19647332b5"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登陆后/u50.png"}},
{
          "id":"42d9a8efb6124ad185e52e19647332b5",
          "label":"set",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":false,
          "style":{
            "location":{
              "x":1127,
              "y":87},
            "size":{
              "width":40,
              "height":61},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c34860e6b57346d08493b9b7f1162b9a",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":40,
                  "height":61}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"55d523e4cec84529a6d6e8b83314a0aa",
                  "label":"设置与退出",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":40,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ab771dd503114b52a1be734b0cbbd5b0",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":40,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/登陆后/设置与退出_u54.png"}},
{
                  "id":"cae173373a9148c09855542a0f87e628",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":40,
                      "height":31}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5e9e8850131c4c2db2ceead6820c18cc",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":30},
                        "size":{
                          "width":40,
                          "height":31}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/登陆后/u56.png"}}]}]},
{
          "id":"11e5fb681041429984b6023ea8a1d9bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":280,
              "y":180},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b30f42bfaf4446eb59fd442d020f561",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":280,
                  "y":180},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b51ba1a17d6640d5bd1bb68d8e9b35ed",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":227},
            "size":{
              "width":887,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/发布公告页/u48_line.png"}},
{
          "id":"3c2f4904017e47bc8e02f93bf936ea75",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":280,
              "y":381},
            "size":{
              "width":49,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a895324330e84f06a50b5115189cad1b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":280,
                  "y":381},
                "size":{
                  "width":49,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ac1581a83ecd4f93bdef1650cf8cd240",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":416},
            "size":{
              "width":437,
              "height":37}},
          "adaptiveStyles":{
},
          "placeholderText":"请输入标题"},
{
          "id":"edf644c3b058476cb8a378291330e946",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":280,
              "y":501},
            "size":{
              "width":49,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98379d91822949b798670a71ef35fbbe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":280,
                  "y":501},
                "size":{
                  "width":49,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5027725c693a4fbba9c0b80d34e8197e",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":536},
            "size":{
              "width":640,
              "height":323}},
          "adaptiveStyles":{
}},
{
          "id":"481bc3a634084c3fbbe817e2df8a7081",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"25px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":282,
              "y":898},
            "size":{
              "width":128,
              "height":60},
            "cornerRadiusTopLeft":"5",
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2bea33f95a3041e48382cc11b400e16b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"25px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":282,
                  "y":898},
                "size":{
                  "width":128,
                  "height":60},
                "cornerRadiusTopLeft":"5",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/发布公告页/u61.png"}},
{
          "id":"6a749b64772d4732a6007503f7027828",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":280,
              "y":264},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96b420a6b82145f0bd1107e814c57fb2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":280,
                  "y":264},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bd915daf06294759b59eb9f4a3345af2",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":280,
              "y":302},
            "size":{
              "width":437,
              "height":44}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "dace685a1fdc4a9f81dfc5b8a819a22b":{
      "scriptId":"u0"},
    "6b9d749187d647aa96569ebc13ac3ed0":{
      "scriptId":"u1"},
    "ae06f51d46b042a0a68c6376cd7f40c3":{
      "scriptId":"u2"},
    "4b31e4cdb2574bfab0ce8a038bc7cb4a":{
      "scriptId":"u3"},
    "43a9083ee36c49a1b62b6ab0f0263ad6":{
      "scriptId":"u4"},
    "e9f033a5ed5d45ee89257b86b37637cb":{
      "scriptId":"u5"},
    "28900071ccbb4ed0b9e162cfa9b5e4f2":{
      "scriptId":"u6"},
    "7a105f5439814b5eb88223fef1e146fb":{
      "scriptId":"u7"},
    "87c89a402aca4c94ae622ac574b5a488":{
      "scriptId":"u8"},
    "ee42fe2748f3427fb47dfbb5f52a7b62":{
      "scriptId":"u9"},
    "ba4188170d0c4568b1a319217c820a72":{
      "scriptId":"u10"},
    "417dbb67d92646a787124ada4dbf44d2":{
      "scriptId":"u11"},
    "19e247deafcb4ba5b498cb15c0df2c63":{
      "scriptId":"u12"},
    "e2028eecb1e44f7b84273317d91fc020":{
      "scriptId":"u13"},
    "d43ab6da874d4c138da951e5db524b53":{
      "scriptId":"u14"},
    "98320176397348e2a6a6fcd86cd22083":{
      "scriptId":"u15"},
    "31c92e0f00484723994e7baf0570366d":{
      "scriptId":"u16"},
    "d84eea71bc2e46cea2053bd4c5e329c5":{
      "scriptId":"u17"},
    "683b0d5afbed47d490fd2b266c54ff26":{
      "scriptId":"u18"},
    "bd0900b0562c41b6926c338f1a9406c5":{
      "scriptId":"u19"},
    "03604c1325af410597a935df84e0c765":{
      "scriptId":"u20"},
    "4a14988436b24cddb2c161fda613462a":{
      "scriptId":"u21"},
    "b7f05b32b4db4fefad898c2fd2e7e4ac":{
      "scriptId":"u22"},
    "ee4b7dc3a36a446395680ba2b7e9be16":{
      "scriptId":"u23"},
    "f73ce96138de4f06bf9dc6b3e2387b0e":{
      "scriptId":"u24"},
    "29dfb9acddfb41818cb04efdb411c5d7":{
      "scriptId":"u25"},
    "9b6970b4d0c84399926eaf130c7e89d1":{
      "scriptId":"u26"},
    "1db092431a9d4725bdc47062664204c1":{
      "scriptId":"u27"},
    "7c259ec7ca454fc5b534c31296b325be":{
      "scriptId":"u28"},
    "765c5dc0965a4fa28f1b63c2d33b5650":{
      "scriptId":"u29"},
    "7507b50f199b4e968cb3793c910b65f7":{
      "scriptId":"u30"},
    "269193dd2f024777af043bdc67e51ee0":{
      "scriptId":"u31"},
    "42462e330ab14995a9299fd6673e05b7":{
      "scriptId":"u32"},
    "5e4c1da4b18a4436a02ac9670d2e7ea8":{
      "scriptId":"u33"},
    "2c93728ce25c4c3f93735c812d3ecbe5":{
      "scriptId":"u34"},
    "eb48ff5467b740a486e5e88817bb29c3":{
      "scriptId":"u35"},
    "2fd7c89b44ed4f30b3ce0810e45bb9d3":{
      "scriptId":"u36"},
    "2d8d6707971f4211a15d45d69e5d4644":{
      "scriptId":"u37"},
    "83716c3f19ac433cb22f81b93a0b9de7":{
      "scriptId":"u38"},
    "cdc949bd3e5647a1ae9810ce1ff74d37":{
      "scriptId":"u39"},
    "42d9a8efb6124ad185e52e19647332b5":{
      "scriptId":"u40"},
    "c34860e6b57346d08493b9b7f1162b9a":{
      "scriptId":"u41"},
    "55d523e4cec84529a6d6e8b83314a0aa":{
      "scriptId":"u42"},
    "ab771dd503114b52a1be734b0cbbd5b0":{
      "scriptId":"u43"},
    "cae173373a9148c09855542a0f87e628":{
      "scriptId":"u44"},
    "5e9e8850131c4c2db2ceead6820c18cc":{
      "scriptId":"u45"},
    "11e5fb681041429984b6023ea8a1d9bd":{
      "scriptId":"u46"},
    "5b30f42bfaf4446eb59fd442d020f561":{
      "scriptId":"u47"},
    "b51ba1a17d6640d5bd1bb68d8e9b35ed":{
      "scriptId":"u48"},
    "3c2f4904017e47bc8e02f93bf936ea75":{
      "scriptId":"u49"},
    "a895324330e84f06a50b5115189cad1b":{
      "scriptId":"u50"},
    "ac1581a83ecd4f93bdef1650cf8cd240":{
      "scriptId":"u51"},
    "edf644c3b058476cb8a378291330e946":{
      "scriptId":"u52"},
    "98379d91822949b798670a71ef35fbbe":{
      "scriptId":"u53"},
    "5027725c693a4fbba9c0b80d34e8197e":{
      "scriptId":"u54"},
    "481bc3a634084c3fbbe817e2df8a7081":{
      "scriptId":"u55"},
    "2bea33f95a3041e48382cc11b400e16b":{
      "scriptId":"u56"},
    "6a749b64772d4732a6007503f7027828":{
      "scriptId":"u57"},
    "96b420a6b82145f0bd1107e814c57fb2":{
      "scriptId":"u58"},
    "bd915daf06294759b59eb9f4a3345af2":{
      "scriptId":"u59"}}});