$axure.loadCurrentPage({
  "url":"公告栏主页面.html",
  "generationDate":new Date(1491295963682.02),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9ce61805b49a46e89366997b0b0c7fd0",
    "type":"Axure:Page",
    "name":"公告栏主页面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"87b298dedc504773b3ddab08768ca086",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "size":{
              "width":1200,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ca36c7e9c59418d9142e5be26778207",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "size":{
                  "width":1200,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u0.png"}},
{
          "id":"488ac7925f3c4ef7b79f4cafca058b4c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":27,
              "y":0},
            "size":{
              "width":202,
              "height":118}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ea292419a1a4a459339d6b498c50d2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":27,
                  "y":0},
                "size":{
                  "width":202,
                  "height":118}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登陆后",
                      "target":{
                        "targetType":"page",
                        "url":"登陆后.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1e922a350c8540f2a88ce9af721c6fe9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1051,
              "y":20},
            "size":{
              "width":80,
              "height":80},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"100"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a36e8c798e6f42b58e5bed4406525bfa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1051,
                  "y":20},
                "size":{
                  "width":80,
                  "height":80},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"100"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u4.png"}},
{
          "id":"71c2549dda57414e88ca337eaa8bf29f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":0,
              "y":130},
            "size":{
              "width":230,
              "height":660}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8fe43dd84b1849f3b703ae6230887ae2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":0,
                  "y":130},
                "size":{
                  "width":230,
                  "height":660}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/公告栏主页面/u6.png"}},
{
          "id":"973d3036f62c4cc9a728031f9147c938",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":213},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"609e48a01adc46b6b7cd7995c11eeadb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":213},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登陆后",
                      "target":{
                        "targetType":"page",
                        "url":"登陆后.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"75eb3db1f30146d4ab022af41b41459d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":308},
            "size":{
              "width":97,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c26d9e3436842e5955edaca716a1dff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":308},
                "size":{
                  "width":97,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 公告栏主页面",
                      "target":{
                        "targetType":"page",
                        "url":"公告栏主页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c4ef4c48339f481ea8f2626a58954f8a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":400},
            "size":{
              "width":97,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a63f116641146f980d03c635bad8f12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":400},
                "size":{
                  "width":97,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 讨论区主页面",
                      "target":{
                        "targetType":"page",
                        "url":"讨论区主页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"82bf9e75d7494531984294ab0eaa305f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":490},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2dcc79b897fc4ac8a6847ab48cdd3e77",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":490},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 成绩管理主页面",
                      "target":{
                        "targetType":"page",
                        "url":"成绩管理主页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9d9793232359442bb8aaaa86d62f2e85",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF363636},
            "location":{
              "x":0,
              "y":790},
            "size":{
              "width":1200,
              "height":180}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e37e98196f2446a4a8fd96215bbca197",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF363636},
                "location":{
                  "x":0,
                  "y":790},
                "size":{
                  "width":1200,
                  "height":180}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u18.png"}},
{
          "id":"8564b3a006a2404ca6b62192ece627fb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":59,
              "y":815},
            "size":{
              "width":87,
              "height":85}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"766740490fd646099470ea6556e78684",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":59,
                  "y":815},
                "size":{
                  "width":87,
                  "height":85}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u20.jpg"}},
{
          "id":"1facdb4b492e41a7893ca823c708e2e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'方正舒体 Regular', '方正舒体'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":45,
              "y":910},
            "size":{
              "width":126,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19b0aa7691fc42eb81b2d95417896621",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'方正舒体 Regular', '方正舒体'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":45,
                  "y":910},
                "size":{
                  "width":126,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7eee776af3c34cf6984fc649fa972bd6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":600,
              "y":815},
            "size":{
              "width":117,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8a1c5eb5bc94af9a8a418bc265ffdc6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":600,
                  "y":815},
                "size":{
                  "width":117,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9f023025bf17483c8beefb0e880b7aae",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":600,
              "y":872},
            "size":{
              "width":77,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d7d95ad0d634fcbad475d67a1a32015",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":600,
                  "y":872},
                "size":{
                  "width":77,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b170094a8537426e8c1f4b25801e0be9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":693,
              "y":872},
            "size":{
              "width":77,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"464a542f4a9e4ecda5827fd3bb6ec264",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":693,
                  "y":872},
                "size":{
                  "width":77,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"557c505a660c420db60578950e4ee9f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":600,
              "y":911},
            "size":{
              "width":77,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04c3865ad3094140907e30264687cdd4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":600,
                  "y":911},
                "size":{
                  "width":77,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"02bced087e0b472e8152903d7e070a0d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":691,
              "y":911},
            "size":{
              "width":77,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac4c087b93344d45917f17447a8a7c3e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":691,
                  "y":911},
                "size":{
                  "width":77,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8a4bd84743d84f119986398e440c8026",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":920,
              "y":815},
            "size":{
              "width":117,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1815ad85298b4ecba1e21560e75a8061",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":920,
                  "y":815},
                "size":{
                  "width":117,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"639024cb31784a69902b91f2e0997849",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":920,
              "y":872},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ce4d9cb4ff84113bd696868c2c86907",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":920,
                  "y":872},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u36.png"}},
{
          "id":"4916816cb994464c9b709412e7328000",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1000,
              "y":872},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a4a3eb7c79a4d1bbc6b31d69dcc0830",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1000,
                  "y":872},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u36.png"}},
{
          "id":"ecbeea1e990246d0a9b9649edfa75120",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":213},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e2077133f9541c7b7c2381a5a37a0eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":310,
                  "y":213},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"024f639b5c364f0f844f8a1e6f2d9534",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Gill Sans Ultra Bold', 'Gill Sans'",
            "fontSize":"36px",
            "fontWeight":"800",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF66FF66},
            "location":{
              "x":462,
              "y":217},
            "size":{
              "width":30,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b642b4897f44300833c56461e6827c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Gill Sans Ultra Bold', 'Gill Sans'",
                "fontSize":"36px",
                "fontWeight":"800",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF66FF66},
                "location":{
                  "x":462,
                  "y":217},
                "size":{
                  "width":30,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 发布公告页",
                      "target":{
                        "targetType":"page",
                        "url":"发布公告页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/课件管理页/u72.png"}},
{
          "id":"ec926383639f4d52a34d52b504585fe2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":1134,
              "y":55},
            "size":{
              "width":24,
              "height":18},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2a64a2cc14448569b2df7bb3f96c62b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":1134,
                  "y":55},
                "size":{
                  "width":24,
                  "height":18},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"切换 set",
                      "objectsToFades":[{
                          "objectPath":["337cd10305394117b0c10b670b25deae"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登陆后/u50.png"}},
{
          "id":"337cd10305394117b0c10b670b25deae",
          "label":"set",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":false,
          "style":{
            "location":{
              "x":1127,
              "y":87},
            "size":{
              "width":40,
              "height":61},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b9fce95af3440e783b2d16d117f19e5",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":40,
                  "height":61}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"84369b937f774d569c439a6504bdb684",
                  "label":"设置与退出",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":40,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3faabcd53cc04b36b95d76e527af1cd3",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":40,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/登陆后/设置与退出_u54.png"}},
{
                  "id":"d601e0d3a0434dfb9698d9a1cd5812bd",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":40,
                      "height":31}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"81c0e8c0b9ec47a8bcd8ef3c8dc30ff9",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":30},
                        "size":{
                          "width":40,
                          "height":31}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/登陆后/u56.png"}}]}]},
{
          "id":"d439314673924cd3a0454cd5ac1f0d1c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":310,
              "y":276},
            "size":{
              "width":630,
              "height":214}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab8209e987864bab88b14a8a256f9f4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":310,
                  "y":276},
                "size":{
                  "width":630,
                  "height":214}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a92bbb01a6e349c4b74b75254abc5ee4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":310,
              "y":507},
            "size":{
              "width":630,
              "height":214}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a17e87dd7d8a489dad060bb0460fb971",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":310,
                  "y":507},
                "size":{
                  "width":630,
                  "height":214}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c53651744c8e42e7a406807e6110df00",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":711},
            "size":{
              "width":640,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/公告栏主页面/u54_line.png"}},
{
          "id":"deefb3d846664964bdf3602482485fda",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":310,
              "y":731},
            "size":{
              "width":100,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5979c80935e40a8a17db0b3f8be3c92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":310,
                  "y":731},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/公告栏主页面/u55.png"}},
{
          "id":"17a462432942478a99f04af39e3716a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":420,
              "y":731},
            "size":{
              "width":30,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c81b1fb0e8104b628287d825a2dc9202",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":420,
                  "y":731},
                "size":{
                  "width":30,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/公告栏主页面/u57.png"}},
{
          "id":"6d8196d89f7845c6b439ae2338c18fd6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":460,
              "y":731},
            "size":{
              "width":30,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78647e5d81914fbebadbda52db6c7585",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":460,
                  "y":731},
                "size":{
                  "width":30,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/公告栏主页面/u57.png"}},
{
          "id":"e87671924bc14d2ebdc60aec72833227",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":500,
              "y":731},
            "size":{
              "width":30,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dcf24ee3743d449c87939726af447a1d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":500,
                  "y":731},
                "size":{
                  "width":30,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/公告栏主页面/u57.png"}},
{
          "id":"603d073ad7f549709a0e70b7751cfd3e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":540,
              "y":731},
            "size":{
              "width":30,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d9ea3cc55894082b84d81115c66aaf0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":540,
                  "y":731},
                "size":{
                  "width":30,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/公告栏主页面/u57.png"}},
{
          "id":"bfcfa5adbedd4370ba5137ff416db783",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":580,
              "y":731},
            "size":{
              "width":30,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d1bc78340da40d1ab3f80f7e9688563",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":580,
                  "y":731},
                "size":{
                  "width":30,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/公告栏主页面/u57.png"}},
{
          "id":"833abd7a30634e45bac48127f1a87a33",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":620,
              "y":731},
            "size":{
              "width":30,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0066fd9678424974bf27f9411f601d74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":620,
                  "y":731},
                "size":{
                  "width":30,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/公告栏主页面/u57.png"}},
{
          "id":"76006c74d2f34890a45f505fffb3f205",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":727,
              "y":731},
            "size":{
              "width":30,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23452478be914eb9b480e61b52f8c1f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":727,
                  "y":731},
                "size":{
                  "width":30,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/公告栏主页面/u57.png"}},
{
          "id":"bfea668c7c094f0ba64368edfa7f3637",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":767,
              "y":731},
            "size":{
              "width":30,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fae6d7b42f3f452198cf14e25a83e8f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":767,
                  "y":731},
                "size":{
                  "width":30,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/公告栏主页面/u57.png"}},
{
          "id":"04afff8a3b5e452c94ba63e370691073",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":807,
              "y":731},
            "size":{
              "width":30,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"682caec684d24ebaba80759d424af6a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":807,
                  "y":731},
                "size":{
                  "width":30,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/公告栏主页面/u57.png"}},
{
          "id":"81b6916079b746f8b099b88635e824c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":847,
              "y":731},
            "size":{
              "width":100,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"371976624b1243b5842439c275012f48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":847,
                  "y":731},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/公告栏主页面/u55.png"}},
{
          "id":"ce8cda6386a34fe4a33f7fb664457d85",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":657,
              "y":732},
            "size":{
              "width":64,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7daa8afe071848b085ccba4cade5b049",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":657,
                  "y":732},
                "size":{
                  "width":64,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"82fe48f3b1f44b68950ab0eb7c04337a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":991,
              "y":207},
            "size":{
              "width":200,
              "height":293},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5958452cfdde4fb696ec662a3bc4d3a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":991,
                  "y":207},
                "size":{
                  "width":200,
                  "height":293},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/公告栏主页面/u79.png"}},
{
          "id":"07093e5463204d3a91b30e417cb59bc0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"25px",
            "location":{
              "x":1000,
              "y":214},
            "size":{
              "width":101,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fad871df7db1406db937cdcb43a7a677",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"25px",
                "location":{
                  "x":1000,
                  "y":214},
                "size":{
                  "width":101,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"db283293b8fe456dbc47fb55353e7f8f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":1000,
              "y":262},
            "size":{
              "width":129,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42b625fd00974ea390e1039c75e2cc3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":1000,
                  "y":262},
                "size":{
                  "width":129,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3eb5685390d94dc29292603939188251",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":1000,
              "y":300},
            "size":{
              "width":177,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0be59f5392ae46e78629099995566f4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":1000,
                  "y":300},
                "size":{
                  "width":177,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f0ef582dc81042019267b5e4b22ec353",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":1000,
              "y":338},
            "size":{
              "width":129,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"670ae3598f984144930d476f6503de75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":1000,
                  "y":338},
                "size":{
                  "width":129,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d6a47ff7de642aea0be849d67fe4365",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":1000,
              "y":376},
            "size":{
              "width":140,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d85b05f8b0434de1b20aee5d4956a6d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":1000,
                  "y":376},
                "size":{
                  "width":140,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b2b5f11066ff4a668ebaf6347170f636",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":1000,
              "y":414},
            "size":{
              "width":105,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1b616a930684436a968fbda7b52c6b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":1000,
                  "y":414},
                "size":{
                  "width":105,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"20fedfb797784bd98cc347803b089585",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":1000,
              "y":452},
            "size":{
              "width":129,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c3da01ed8df41cdb08493921b776fc2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":1000,
                  "y":452},
                "size":{
                  "width":129,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"263b1524d3f94b02be4052c6271af83d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":480},
            "size":{
              "width":640,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/公告栏主页面/u54_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "87b298dedc504773b3ddab08768ca086":{
      "scriptId":"u0"},
    "3ca36c7e9c59418d9142e5be26778207":{
      "scriptId":"u1"},
    "488ac7925f3c4ef7b79f4cafca058b4c":{
      "scriptId":"u2"},
    "9ea292419a1a4a459339d6b498c50d2a":{
      "scriptId":"u3"},
    "1e922a350c8540f2a88ce9af721c6fe9":{
      "scriptId":"u4"},
    "a36e8c798e6f42b58e5bed4406525bfa":{
      "scriptId":"u5"},
    "71c2549dda57414e88ca337eaa8bf29f":{
      "scriptId":"u6"},
    "8fe43dd84b1849f3b703ae6230887ae2":{
      "scriptId":"u7"},
    "973d3036f62c4cc9a728031f9147c938":{
      "scriptId":"u8"},
    "609e48a01adc46b6b7cd7995c11eeadb":{
      "scriptId":"u9"},
    "75eb3db1f30146d4ab022af41b41459d":{
      "scriptId":"u10"},
    "9c26d9e3436842e5955edaca716a1dff":{
      "scriptId":"u11"},
    "c4ef4c48339f481ea8f2626a58954f8a":{
      "scriptId":"u12"},
    "1a63f116641146f980d03c635bad8f12":{
      "scriptId":"u13"},
    "82bf9e75d7494531984294ab0eaa305f":{
      "scriptId":"u14"},
    "2dcc79b897fc4ac8a6847ab48cdd3e77":{
      "scriptId":"u15"},
    "9d9793232359442bb8aaaa86d62f2e85":{
      "scriptId":"u16"},
    "e37e98196f2446a4a8fd96215bbca197":{
      "scriptId":"u17"},
    "8564b3a006a2404ca6b62192ece627fb":{
      "scriptId":"u18"},
    "766740490fd646099470ea6556e78684":{
      "scriptId":"u19"},
    "1facdb4b492e41a7893ca823c708e2e3":{
      "scriptId":"u20"},
    "19b0aa7691fc42eb81b2d95417896621":{
      "scriptId":"u21"},
    "7eee776af3c34cf6984fc649fa972bd6":{
      "scriptId":"u22"},
    "e8a1c5eb5bc94af9a8a418bc265ffdc6":{
      "scriptId":"u23"},
    "9f023025bf17483c8beefb0e880b7aae":{
      "scriptId":"u24"},
    "9d7d95ad0d634fcbad475d67a1a32015":{
      "scriptId":"u25"},
    "b170094a8537426e8c1f4b25801e0be9":{
      "scriptId":"u26"},
    "464a542f4a9e4ecda5827fd3bb6ec264":{
      "scriptId":"u27"},
    "557c505a660c420db60578950e4ee9f1":{
      "scriptId":"u28"},
    "04c3865ad3094140907e30264687cdd4":{
      "scriptId":"u29"},
    "02bced087e0b472e8152903d7e070a0d":{
      "scriptId":"u30"},
    "ac4c087b93344d45917f17447a8a7c3e":{
      "scriptId":"u31"},
    "8a4bd84743d84f119986398e440c8026":{
      "scriptId":"u32"},
    "1815ad85298b4ecba1e21560e75a8061":{
      "scriptId":"u33"},
    "639024cb31784a69902b91f2e0997849":{
      "scriptId":"u34"},
    "7ce4d9cb4ff84113bd696868c2c86907":{
      "scriptId":"u35"},
    "4916816cb994464c9b709412e7328000":{
      "scriptId":"u36"},
    "9a4a3eb7c79a4d1bbc6b31d69dcc0830":{
      "scriptId":"u37"},
    "ecbeea1e990246d0a9b9649edfa75120":{
      "scriptId":"u38"},
    "1e2077133f9541c7b7c2381a5a37a0eb":{
      "scriptId":"u39"},
    "024f639b5c364f0f844f8a1e6f2d9534":{
      "scriptId":"u40"},
    "2b642b4897f44300833c56461e6827c6":{
      "scriptId":"u41"},
    "ec926383639f4d52a34d52b504585fe2":{
      "scriptId":"u42"},
    "c2a64a2cc14448569b2df7bb3f96c62b":{
      "scriptId":"u43"},
    "337cd10305394117b0c10b670b25deae":{
      "scriptId":"u44"},
    "9b9fce95af3440e783b2d16d117f19e5":{
      "scriptId":"u45"},
    "84369b937f774d569c439a6504bdb684":{
      "scriptId":"u46"},
    "3faabcd53cc04b36b95d76e527af1cd3":{
      "scriptId":"u47"},
    "d601e0d3a0434dfb9698d9a1cd5812bd":{
      "scriptId":"u48"},
    "81c0e8c0b9ec47a8bcd8ef3c8dc30ff9":{
      "scriptId":"u49"},
    "d439314673924cd3a0454cd5ac1f0d1c":{
      "scriptId":"u50"},
    "ab8209e987864bab88b14a8a256f9f4f":{
      "scriptId":"u51"},
    "a92bbb01a6e349c4b74b75254abc5ee4":{
      "scriptId":"u52"},
    "a17e87dd7d8a489dad060bb0460fb971":{
      "scriptId":"u53"},
    "c53651744c8e42e7a406807e6110df00":{
      "scriptId":"u54"},
    "deefb3d846664964bdf3602482485fda":{
      "scriptId":"u55"},
    "f5979c80935e40a8a17db0b3f8be3c92":{
      "scriptId":"u56"},
    "17a462432942478a99f04af39e3716a0":{
      "scriptId":"u57"},
    "c81b1fb0e8104b628287d825a2dc9202":{
      "scriptId":"u58"},
    "6d8196d89f7845c6b439ae2338c18fd6":{
      "scriptId":"u59"},
    "78647e5d81914fbebadbda52db6c7585":{
      "scriptId":"u60"},
    "e87671924bc14d2ebdc60aec72833227":{
      "scriptId":"u61"},
    "dcf24ee3743d449c87939726af447a1d":{
      "scriptId":"u62"},
    "603d073ad7f549709a0e70b7751cfd3e":{
      "scriptId":"u63"},
    "2d9ea3cc55894082b84d81115c66aaf0":{
      "scriptId":"u64"},
    "bfcfa5adbedd4370ba5137ff416db783":{
      "scriptId":"u65"},
    "8d1bc78340da40d1ab3f80f7e9688563":{
      "scriptId":"u66"},
    "833abd7a30634e45bac48127f1a87a33":{
      "scriptId":"u67"},
    "0066fd9678424974bf27f9411f601d74":{
      "scriptId":"u68"},
    "76006c74d2f34890a45f505fffb3f205":{
      "scriptId":"u69"},
    "23452478be914eb9b480e61b52f8c1f9":{
      "scriptId":"u70"},
    "bfea668c7c094f0ba64368edfa7f3637":{
      "scriptId":"u71"},
    "fae6d7b42f3f452198cf14e25a83e8f2":{
      "scriptId":"u72"},
    "04afff8a3b5e452c94ba63e370691073":{
      "scriptId":"u73"},
    "682caec684d24ebaba80759d424af6a0":{
      "scriptId":"u74"},
    "81b6916079b746f8b099b88635e824c4":{
      "scriptId":"u75"},
    "371976624b1243b5842439c275012f48":{
      "scriptId":"u76"},
    "ce8cda6386a34fe4a33f7fb664457d85":{
      "scriptId":"u77"},
    "7daa8afe071848b085ccba4cade5b049":{
      "scriptId":"u78"},
    "82fe48f3b1f44b68950ab0eb7c04337a":{
      "scriptId":"u79"},
    "5958452cfdde4fb696ec662a3bc4d3a9":{
      "scriptId":"u80"},
    "07093e5463204d3a91b30e417cb59bc0":{
      "scriptId":"u81"},
    "fad871df7db1406db937cdcb43a7a677":{
      "scriptId":"u82"},
    "db283293b8fe456dbc47fb55353e7f8f":{
      "scriptId":"u83"},
    "42b625fd00974ea390e1039c75e2cc3a":{
      "scriptId":"u84"},
    "3eb5685390d94dc29292603939188251":{
      "scriptId":"u85"},
    "0be59f5392ae46e78629099995566f4f":{
      "scriptId":"u86"},
    "f0ef582dc81042019267b5e4b22ec353":{
      "scriptId":"u87"},
    "670ae3598f984144930d476f6503de75":{
      "scriptId":"u88"},
    "4d6a47ff7de642aea0be849d67fe4365":{
      "scriptId":"u89"},
    "d85b05f8b0434de1b20aee5d4956a6d7":{
      "scriptId":"u90"},
    "b2b5f11066ff4a668ebaf6347170f636":{
      "scriptId":"u91"},
    "e1b616a930684436a968fbda7b52c6b3":{
      "scriptId":"u92"},
    "20fedfb797784bd98cc347803b089585":{
      "scriptId":"u93"},
    "3c3da01ed8df41cdb08493921b776fc2":{
      "scriptId":"u94"},
    "263b1524d3f94b02be4052c6271af83d":{
      "scriptId":"u95"}}});