$axure.loadCurrentPage({
  "url":"课件管理页.html",
  "generationDate":new Date(1491295962988.28),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"17946eb0420d4fd287851255e2aedd2c",
    "type":"Axure:Page",
    "name":"课件管理页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"804cb6ff1c914beea88c687615422517",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "size":{
              "width":1200,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37e1a4915fb146e185aa1994c40d91c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "size":{
                  "width":1200,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u0.png"}},
{
          "id":"1b8bd1a039f34224b0b102b21a8fdf23",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":27,
              "y":0},
            "size":{
              "width":202,
              "height":118}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d1ebc070853441b98440565ca8a7262",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":27,
                  "y":0},
                "size":{
                  "width":202,
                  "height":118}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登陆后",
                      "target":{
                        "targetType":"page",
                        "url":"登陆后.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dbf6d45961a9457b8e061d72497c0a15",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1051,
              "y":20},
            "size":{
              "width":80,
              "height":80},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"100"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a8a98a0b3164a09a95bb7572df96bc0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1051,
                  "y":20},
                "size":{
                  "width":80,
                  "height":80},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"100"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u4.png"}},
{
          "id":"133bbfd0d57d48d2950c079cc83d3766",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":0,
              "y":130},
            "size":{
              "width":230,
              "height":590}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5b0eece7c91490b94cf339ba36d24b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":0,
                  "y":130},
                "size":{
                  "width":230,
                  "height":590}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u6.png"}},
{
          "id":"67e59d28b0564619b9e68981cc114d61",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":213},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e827f4a5c8240f189fb42f7ec243579",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":213},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登陆后",
                      "target":{
                        "targetType":"page",
                        "url":"登陆后.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"62c789fc7dd9402cb93e98a61e87d7a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":308},
            "size":{
              "width":97,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01f5ee8bf4dc46bca57251837ae9f0c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":308},
                "size":{
                  "width":97,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 公告栏主页面",
                      "target":{
                        "targetType":"page",
                        "url":"公告栏主页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b89134882bdc480086b4964b1099ab88",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":400},
            "size":{
              "width":97,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8920f5accff741eb935b5cc0bef9bfe7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":400},
                "size":{
                  "width":97,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 讨论区主页面",
                      "target":{
                        "targetType":"page",
                        "url":"讨论区主页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ecac264b69624a5ab8b3fb5ae2d4e39c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":490},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e57589c969b4902983c9f4e6cadd8c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":490},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 成绩管理主页面",
                      "target":{
                        "targetType":"page",
                        "url":"成绩管理主页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2a447c3457f24d39b80b31951ad93f49",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF363636},
            "location":{
              "x":0,
              "y":720},
            "size":{
              "width":1200,
              "height":180}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be5aa5d105c44555b56412efb7239588",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF363636},
                "location":{
                  "x":0,
                  "y":720},
                "size":{
                  "width":1200,
                  "height":180}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u18.png"}},
{
          "id":"309815084609400493c28c05dbba4ac8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":59,
              "y":745},
            "size":{
              "width":87,
              "height":85}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92e0d9cf8faf4953a5b029b80579a841",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":59,
                  "y":745},
                "size":{
                  "width":87,
                  "height":85}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u20.jpg"}},
{
          "id":"a4509f3f57d647df9b583ed304c79b9f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'方正舒体 Regular', '方正舒体'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":45,
              "y":840},
            "size":{
              "width":126,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8447c8745fda48c6ad53f156130dedc8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'方正舒体 Regular', '方正舒体'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":45,
                  "y":840},
                "size":{
                  "width":126,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"13d905d64d154140ba70f8e713eb3c81",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":600,
              "y":745},
            "size":{
              "width":117,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"122d39832688419db659b9219b5256f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":600,
                  "y":745},
                "size":{
                  "width":117,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8524ff9ce0194e1a98854e14074b486a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":600,
              "y":802},
            "size":{
              "width":77,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89cbd8eb816d4129a953e6862992f93d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":600,
                  "y":802},
                "size":{
                  "width":77,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c4f498d8893549859f0f478a6958beda",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":693,
              "y":802},
            "size":{
              "width":77,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a31f29380e84440896ed40110ab44182",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":693,
                  "y":802},
                "size":{
                  "width":77,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2945fafb46084813a848f1e967f63e3c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":600,
              "y":841},
            "size":{
              "width":77,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf879ba954f24530903ca626c8523dbd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":600,
                  "y":841},
                "size":{
                  "width":77,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fbc191bb83cd4fd79741aa9ca683baec",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":691,
              "y":841},
            "size":{
              "width":77,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64d3932b4a164c46a5d3caecc2cc58d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":691,
                  "y":841},
                "size":{
                  "width":77,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a43592dbcb994fb6b3c8e4172ed32eed",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":920,
              "y":745},
            "size":{
              "width":117,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78bd87911e204939ac05cf504ead3478",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":920,
                  "y":745},
                "size":{
                  "width":117,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"54ab3ea219774ce1b768464c62ba010e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":920,
              "y":802},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6975ec245bb448c8aad6956cb121a161",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":920,
                  "y":802},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u36.png"}},
{
          "id":"8e8902d537e34acba29202272f786893",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1000,
              "y":802},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df8ed643ee924d9cb5d4107d1675c71a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1000,
                  "y":802},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u36.png"}},
{
          "id":"f067a25b84c0419c94414c56908c71ee",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":276},
            "size":{
              "width":87,
              "height":87}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad736d45514d4efab99bd75326048d26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":310,
                  "y":276},
                "size":{
                  "width":87,
                  "height":87}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/课件管理页/u38.jpg"}},
{
          "id":"71d5ae5789644d4fa3276b37bf80c99f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":480,
              "y":276},
            "size":{
              "width":87,
              "height":87}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c1f68a45bd64dc480060d018319cb29",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":480,
                  "y":276},
                "size":{
                  "width":87,
                  "height":87}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/课件管理页/u38.jpg"}},
{
          "id":"929b484e5f41419d9b5d26a4e0e4e75b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":650,
              "y":276},
            "size":{
              "width":87,
              "height":87}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ffa6693919964b36bd7c76dbe4ae7adf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":650,
                  "y":276},
                "size":{
                  "width":87,
                  "height":87}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/课件管理页/u38.jpg"}},
{
          "id":"104ea021a28a49cab88cf0c32f265056",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":813,
              "y":276},
            "size":{
              "width":87,
              "height":87}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38556b33187946b29c4b715b59d54340",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":813,
                  "y":276},
                "size":{
                  "width":87,
                  "height":87}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/课件管理页/u38.jpg"}},
{
          "id":"afa107434a8643e3ba18ea11d23f6207",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":438},
            "size":{
              "width":87,
              "height":87}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb5c67768dd447228ab5e9ec6c305f6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":310,
                  "y":438},
                "size":{
                  "width":87,
                  "height":87}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/课件管理页/u38.jpg"}},
{
          "id":"57a854ba1ce1424b9b0d8576684ed30b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":480,
              "y":438},
            "size":{
              "width":87,
              "height":87}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3905644f31ba44a4bd73fb7c3efffb0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":480,
                  "y":438},
                "size":{
                  "width":87,
                  "height":87}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/课件管理页/u38.jpg"}},
{
          "id":"1e6a27fb0e3e490bb42c048cc764063b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":650,
              "y":438},
            "size":{
              "width":87,
              "height":87}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37fa0f19bb594b70a7d7d8b666a83940",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":650,
                  "y":438},
                "size":{
                  "width":87,
                  "height":87}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/课件管理页/u38.jpg"}},
{
          "id":"4ff2b2cc8b664c5a8fcfb8dbef4eb03c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":310,
              "y":373},
            "size":{
              "width":55,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a33e27e248de41e0bdc6907a86279dc3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":310,
                  "y":373},
                "size":{
                  "width":55,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"67aec8a53f0b482ea6c587fe73249bbf",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":480,
              "y":373},
            "size":{
              "width":55,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a10deed4d8746289f7b34e33d733db8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":480,
                  "y":373},
                "size":{
                  "width":55,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2f484865069c47eb96237fadfea68d02",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":650,
              "y":373},
            "size":{
              "width":55,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14200b6e5b13444e8008859e65031e74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":650,
                  "y":373},
                "size":{
                  "width":55,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"927d6c1fd3574e67bb476a45af9f4b47",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":813,
              "y":373},
            "size":{
              "width":55,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c67686002584b5c9b083b023d96efc7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":813,
                  "y":373},
                "size":{
                  "width":55,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bcaef63d98e5446a9c9890c6ff481537",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":310,
              "y":535},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bada7e7d50784a1abccc890faca7dd5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":310,
                  "y":535},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3e374b4298f645db95d33c646f4ed572",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":480,
              "y":535},
            "size":{
              "width":55,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"651e5034cdc347a2a35f0948b8e98cff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":480,
                  "y":535},
                "size":{
                  "width":55,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f642e6b4d7854fd68bbfc65287bf8577",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":650,
              "y":535},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e67a738eb9cc4e4e80177af54a6229be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":650,
                  "y":535},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"716c7b54ac8444d4829cbae502793568",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":980,
              "y":206},
            "size":{
              "width":211,
              "height":364},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2938b562cc794b44aefc56487eed7b42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":980,
                  "y":206},
                "size":{
                  "width":211,
                  "height":364},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/课件管理页/u66.png"}},
{
          "id":"909a2f2e8e51431fb960512037463436",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":213},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9cfbebca0a247858818e66de8d33b25",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":310,
                  "y":213},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b2c1dc1423d0440280b82ba498d5380d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":991,
              "y":213},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab113c27a1b845428e2f83c306a8f8bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":991,
                  "y":213},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 课堂检测管理页",
                      "target":{
                        "targetType":"page",
                        "url":"课堂检测管理页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"42fa0745c8f448469af33810edf6ee80",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Gill Sans Ultra Bold', 'Gill Sans'",
            "fontSize":"36px",
            "fontWeight":"800",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF66FF66},
            "location":{
              "x":462,
              "y":217},
            "size":{
              "width":30,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc385b6cf8ef413c9511e6ac02a24605",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Gill Sans Ultra Bold', 'Gill Sans'",
                "fontSize":"36px",
                "fontWeight":"800",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF66FF66},
                "location":{
                  "x":462,
                  "y":217},
                "size":{
                  "width":30,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/课件管理页/u72.png"}},
{
          "id":"4497c79b4734406280334f699b5b4a29",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Gill Sans Ultra Bold', 'Gill Sans'",
            "fontSize":"36px",
            "fontWeight":"800",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF66FF66},
            "location":{
              "x":1130,
              "y":216},
            "size":{
              "width":30,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c23cd5c529ac49659ebacae2f64247cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Gill Sans Ultra Bold', 'Gill Sans'",
                "fontSize":"36px",
                "fontWeight":"800",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF66FF66},
                "location":{
                  "x":1130,
                  "y":216},
                "size":{
                  "width":30,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/课件管理页/u72.png"}},
{
          "id":"bcc105986d9e425f9db4316286a3248b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":991,
              "y":276},
            "size":{
              "width":136,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50589ed583ea40f3a6a288a4b7392e28",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":991,
                  "y":276},
                "size":{
                  "width":136,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 某次测试页",
                      "target":{
                        "targetType":"page",
                        "url":"某次测试页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5d019c448a5d43d38b7a4ec38ffc3655",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":991,
              "y":314},
            "size":{
              "width":136,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"325cbfd2aeff4f8f8e4e7738b60e9e34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":991,
                  "y":314},
                "size":{
                  "width":136,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4cb6ae06bc684e00ab545ac72a55d5ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":991,
              "y":352},
            "size":{
              "width":136,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aee1a2743ee444008c1c2fa199021e30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":991,
                  "y":352},
                "size":{
                  "width":136,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5c8a93e5f5154586a9bc6f5e549ca52e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":991,
              "y":390},
            "size":{
              "width":136,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7e9d621ec584acda91a3214ffc93c7e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":991,
                  "y":390},
                "size":{
                  "width":136,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"68aa2ed9b4cd4a84ac042465f0517c65",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":991,
              "y":428},
            "size":{
              "width":136,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a7b0aa97984431f964bf7b75ef00f63",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":991,
                  "y":428},
                "size":{
                  "width":136,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"34ab30fdf9464fbaa3b6501ddb87d0eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":991,
              "y":466},
            "size":{
              "width":136,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1984914b873e4febb234daeaed5109a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":991,
                  "y":466},
                "size":{
                  "width":136,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"16a3b0f6904e4aa4961569e185a21533",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":991,
              "y":504},
            "size":{
              "width":136,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6753b803e4a4478c8d45929ca661ff9a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":991,
                  "y":504},
                "size":{
                  "width":136,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0dedf51066494569a3f0d5524461d590",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1035.5,
              "y":540},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0231b517abc44fe5af291af410234337",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1035.5,
                  "y":540},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 课堂检测管理页",
                      "target":{
                        "targetType":"page",
                        "url":"课堂检测管理页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/课件管理页/u90.png"}},
{
          "id":"5343a3763e2f4d83be9554378cb2f1ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":1134,
              "y":55},
            "size":{
              "width":24,
              "height":18},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"299c885c96274c5fb78fe7cee49dce5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":1134,
                  "y":55},
                "size":{
                  "width":24,
                  "height":18},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"切换 set",
                      "objectsToFades":[{
                          "objectPath":["32a595ca2704491b963af34b02a032d4"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登陆后/u50.png"}},
{
          "id":"32a595ca2704491b963af34b02a032d4",
          "label":"set",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":false,
          "style":{
            "location":{
              "x":1127,
              "y":87},
            "size":{
              "width":40,
              "height":61},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3842a207d5544fbbf6f7db660e05585",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":40,
                  "height":61}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0020e478b912467bbb0a2036cc0df12a",
                  "label":"设置与退出",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":40,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"908995b0d6a34070a0454722948599f6",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":40,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/登陆后/设置与退出_u54.png"}},
{
                  "id":"3266e229329f455195d8a8fb027c6cf0",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":40,
                      "height":31}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6791a9eae7bf4f6ab0899cffdfcb584b",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":30},
                        "size":{
                          "width":40,
                          "height":31}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/登陆后/u56.png"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "804cb6ff1c914beea88c687615422517":{
      "scriptId":"u0"},
    "37e1a4915fb146e185aa1994c40d91c9":{
      "scriptId":"u1"},
    "1b8bd1a039f34224b0b102b21a8fdf23":{
      "scriptId":"u2"},
    "2d1ebc070853441b98440565ca8a7262":{
      "scriptId":"u3"},
    "dbf6d45961a9457b8e061d72497c0a15":{
      "scriptId":"u4"},
    "7a8a98a0b3164a09a95bb7572df96bc0":{
      "scriptId":"u5"},
    "133bbfd0d57d48d2950c079cc83d3766":{
      "scriptId":"u6"},
    "b5b0eece7c91490b94cf339ba36d24b8":{
      "scriptId":"u7"},
    "67e59d28b0564619b9e68981cc114d61":{
      "scriptId":"u8"},
    "9e827f4a5c8240f189fb42f7ec243579":{
      "scriptId":"u9"},
    "62c789fc7dd9402cb93e98a61e87d7a0":{
      "scriptId":"u10"},
    "01f5ee8bf4dc46bca57251837ae9f0c2":{
      "scriptId":"u11"},
    "b89134882bdc480086b4964b1099ab88":{
      "scriptId":"u12"},
    "8920f5accff741eb935b5cc0bef9bfe7":{
      "scriptId":"u13"},
    "ecac264b69624a5ab8b3fb5ae2d4e39c":{
      "scriptId":"u14"},
    "5e57589c969b4902983c9f4e6cadd8c0":{
      "scriptId":"u15"},
    "2a447c3457f24d39b80b31951ad93f49":{
      "scriptId":"u16"},
    "be5aa5d105c44555b56412efb7239588":{
      "scriptId":"u17"},
    "309815084609400493c28c05dbba4ac8":{
      "scriptId":"u18"},
    "92e0d9cf8faf4953a5b029b80579a841":{
      "scriptId":"u19"},
    "a4509f3f57d647df9b583ed304c79b9f":{
      "scriptId":"u20"},
    "8447c8745fda48c6ad53f156130dedc8":{
      "scriptId":"u21"},
    "13d905d64d154140ba70f8e713eb3c81":{
      "scriptId":"u22"},
    "122d39832688419db659b9219b5256f1":{
      "scriptId":"u23"},
    "8524ff9ce0194e1a98854e14074b486a":{
      "scriptId":"u24"},
    "89cbd8eb816d4129a953e6862992f93d":{
      "scriptId":"u25"},
    "c4f498d8893549859f0f478a6958beda":{
      "scriptId":"u26"},
    "a31f29380e84440896ed40110ab44182":{
      "scriptId":"u27"},
    "2945fafb46084813a848f1e967f63e3c":{
      "scriptId":"u28"},
    "bf879ba954f24530903ca626c8523dbd":{
      "scriptId":"u29"},
    "fbc191bb83cd4fd79741aa9ca683baec":{
      "scriptId":"u30"},
    "64d3932b4a164c46a5d3caecc2cc58d2":{
      "scriptId":"u31"},
    "a43592dbcb994fb6b3c8e4172ed32eed":{
      "scriptId":"u32"},
    "78bd87911e204939ac05cf504ead3478":{
      "scriptId":"u33"},
    "54ab3ea219774ce1b768464c62ba010e":{
      "scriptId":"u34"},
    "6975ec245bb448c8aad6956cb121a161":{
      "scriptId":"u35"},
    "8e8902d537e34acba29202272f786893":{
      "scriptId":"u36"},
    "df8ed643ee924d9cb5d4107d1675c71a":{
      "scriptId":"u37"},
    "f067a25b84c0419c94414c56908c71ee":{
      "scriptId":"u38"},
    "ad736d45514d4efab99bd75326048d26":{
      "scriptId":"u39"},
    "71d5ae5789644d4fa3276b37bf80c99f":{
      "scriptId":"u40"},
    "6c1f68a45bd64dc480060d018319cb29":{
      "scriptId":"u41"},
    "929b484e5f41419d9b5d26a4e0e4e75b":{
      "scriptId":"u42"},
    "ffa6693919964b36bd7c76dbe4ae7adf":{
      "scriptId":"u43"},
    "104ea021a28a49cab88cf0c32f265056":{
      "scriptId":"u44"},
    "38556b33187946b29c4b715b59d54340":{
      "scriptId":"u45"},
    "afa107434a8643e3ba18ea11d23f6207":{
      "scriptId":"u46"},
    "cb5c67768dd447228ab5e9ec6c305f6e":{
      "scriptId":"u47"},
    "57a854ba1ce1424b9b0d8576684ed30b":{
      "scriptId":"u48"},
    "3905644f31ba44a4bd73fb7c3efffb0d":{
      "scriptId":"u49"},
    "1e6a27fb0e3e490bb42c048cc764063b":{
      "scriptId":"u50"},
    "37fa0f19bb594b70a7d7d8b666a83940":{
      "scriptId":"u51"},
    "4ff2b2cc8b664c5a8fcfb8dbef4eb03c":{
      "scriptId":"u52"},
    "a33e27e248de41e0bdc6907a86279dc3":{
      "scriptId":"u53"},
    "67aec8a53f0b482ea6c587fe73249bbf":{
      "scriptId":"u54"},
    "1a10deed4d8746289f7b34e33d733db8":{
      "scriptId":"u55"},
    "2f484865069c47eb96237fadfea68d02":{
      "scriptId":"u56"},
    "14200b6e5b13444e8008859e65031e74":{
      "scriptId":"u57"},
    "927d6c1fd3574e67bb476a45af9f4b47":{
      "scriptId":"u58"},
    "7c67686002584b5c9b083b023d96efc7":{
      "scriptId":"u59"},
    "bcaef63d98e5446a9c9890c6ff481537":{
      "scriptId":"u60"},
    "bada7e7d50784a1abccc890faca7dd5f":{
      "scriptId":"u61"},
    "3e374b4298f645db95d33c646f4ed572":{
      "scriptId":"u62"},
    "651e5034cdc347a2a35f0948b8e98cff":{
      "scriptId":"u63"},
    "f642e6b4d7854fd68bbfc65287bf8577":{
      "scriptId":"u64"},
    "e67a738eb9cc4e4e80177af54a6229be":{
      "scriptId":"u65"},
    "716c7b54ac8444d4829cbae502793568":{
      "scriptId":"u66"},
    "2938b562cc794b44aefc56487eed7b42":{
      "scriptId":"u67"},
    "909a2f2e8e51431fb960512037463436":{
      "scriptId":"u68"},
    "d9cfbebca0a247858818e66de8d33b25":{
      "scriptId":"u69"},
    "b2c1dc1423d0440280b82ba498d5380d":{
      "scriptId":"u70"},
    "ab113c27a1b845428e2f83c306a8f8bf":{
      "scriptId":"u71"},
    "42fa0745c8f448469af33810edf6ee80":{
      "scriptId":"u72"},
    "cc385b6cf8ef413c9511e6ac02a24605":{
      "scriptId":"u73"},
    "4497c79b4734406280334f699b5b4a29":{
      "scriptId":"u74"},
    "c23cd5c529ac49659ebacae2f64247cb":{
      "scriptId":"u75"},
    "bcc105986d9e425f9db4316286a3248b":{
      "scriptId":"u76"},
    "50589ed583ea40f3a6a288a4b7392e28":{
      "scriptId":"u77"},
    "5d019c448a5d43d38b7a4ec38ffc3655":{
      "scriptId":"u78"},
    "325cbfd2aeff4f8f8e4e7738b60e9e34":{
      "scriptId":"u79"},
    "4cb6ae06bc684e00ab545ac72a55d5ba":{
      "scriptId":"u80"},
    "aee1a2743ee444008c1c2fa199021e30":{
      "scriptId":"u81"},
    "5c8a93e5f5154586a9bc6f5e549ca52e":{
      "scriptId":"u82"},
    "d7e9d621ec584acda91a3214ffc93c7e":{
      "scriptId":"u83"},
    "68aa2ed9b4cd4a84ac042465f0517c65":{
      "scriptId":"u84"},
    "3a7b0aa97984431f964bf7b75ef00f63":{
      "scriptId":"u85"},
    "34ab30fdf9464fbaa3b6501ddb87d0eb":{
      "scriptId":"u86"},
    "1984914b873e4febb234daeaed5109a5":{
      "scriptId":"u87"},
    "16a3b0f6904e4aa4961569e185a21533":{
      "scriptId":"u88"},
    "6753b803e4a4478c8d45929ca661ff9a":{
      "scriptId":"u89"},
    "0dedf51066494569a3f0d5524461d590":{
      "scriptId":"u90"},
    "0231b517abc44fe5af291af410234337":{
      "scriptId":"u91"},
    "5343a3763e2f4d83be9554378cb2f1ea":{
      "scriptId":"u92"},
    "299c885c96274c5fb78fe7cee49dce5d":{
      "scriptId":"u93"},
    "32a595ca2704491b963af34b02a032d4":{
      "scriptId":"u94"},
    "f3842a207d5544fbbf6f7db660e05585":{
      "scriptId":"u95"},
    "0020e478b912467bbb0a2036cc0df12a":{
      "scriptId":"u96"},
    "908995b0d6a34070a0454722948599f6":{
      "scriptId":"u97"},
    "3266e229329f455195d8a8fb027c6cf0":{
      "scriptId":"u98"},
    "6791a9eae7bf4f6ab0899cffdfcb584b":{
      "scriptId":"u99"}}});