$axure.loadCurrentPage({
  "url":"登陆后.html",
  "generationDate":new Date(1491295962796),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"5f082c9cf2d342bfa7dacf5e7bc1de98",
    "type":"Axure:Page",
    "name":"登陆后",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"cee9702b8114490db301dad0b152c3e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "size":{
              "width":1200,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95ba5a16870b4b7d90f5ea78fca83930",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "size":{
                  "width":1200,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u0.png"}},
{
          "id":"ceee0b478c9f41249ff1553c60d3891c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":27,
              "y":0},
            "size":{
              "width":202,
              "height":118}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9266f0fb358849138eb8c414c4eb9340",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":27,
                  "y":0},
                "size":{
                  "width":202,
                  "height":118}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登陆后",
                      "target":{
                        "targetType":"page",
                        "url":"登陆后.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3aafc90b25394ddebfdb4e5c3dacdfe0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1051,
              "y":20},
            "size":{
              "width":80,
              "height":80},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"100"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d752c33d6cf7448bbd2d40e3db62043c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1051,
                  "y":20},
                "size":{
                  "width":80,
                  "height":80},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"100"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u4.png"}},
{
          "id":"5697bdf14e784e0b85c3cf25540cb926",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":0,
              "y":130},
            "size":{
              "width":230,
              "height":590}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"854d9f202666406eae02fa1d6cd2956c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":0,
                  "y":130},
                "size":{
                  "width":230,
                  "height":590}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u6.png"}},
{
          "id":"4ec2a28c56044b95afcbe68300e0cc01",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":330,
              "y":200},
            "size":{
              "width":210,
              "height":190}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"380164424ab14d7eb1687bcbf2ee37a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":330,
                  "y":200},
                "size":{
                  "width":210,
                  "height":190}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 课件管理页",
                      "target":{
                        "targetType":"page",
                        "url":"课件管理页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登陆后/u8.png"}},
{
          "id":"8875444e949f418a997649aab224d32a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":213},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc888f0e74fa4a2e8066c0f73324677a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":213},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登陆后",
                      "target":{
                        "targetType":"page",
                        "url":"登陆后.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"87900c0749e1435b965e376e2fdc698b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":308},
            "size":{
              "width":97,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f21cc9e13fb41db9562c0614754f2d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":308},
                "size":{
                  "width":97,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 公告栏主页面",
                      "target":{
                        "targetType":"page",
                        "url":"公告栏主页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"807ac0b1cac84f60b78ba0d78e674ce7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":400},
            "size":{
              "width":97,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24626b8f8f0843488c40514ca15e7acb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":400},
                "size":{
                  "width":97,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 讨论区主页面",
                      "target":{
                        "targetType":"page",
                        "url":"讨论区主页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1f3573a1494c4c4dab4430742ea0554f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":490},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2d4cfb5282f4516aa2318ce3f95feb7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":490},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 成绩管理主页面",
                      "target":{
                        "targetType":"page",
                        "url":"成绩管理主页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c6e5957439da478cb06cb207ab08a2f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF363636},
            "location":{
              "x":0,
              "y":720},
            "size":{
              "width":1200,
              "height":180}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be0b974592744b6687d8e8a0ec90f3d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF363636},
                "location":{
                  "x":0,
                  "y":720},
                "size":{
                  "width":1200,
                  "height":180}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u18.png"}},
{
          "id":"25fa01ebd81f4c2fbc518ceaf82fab1e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":59,
              "y":745},
            "size":{
              "width":87,
              "height":85}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0dd26fb92426421da65e6e77467a0109",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":59,
                  "y":745},
                "size":{
                  "width":87,
                  "height":85}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u20.jpg"}},
{
          "id":"2bd35ce570274e99823383d77cd89faf",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'方正舒体 Regular', '方正舒体'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":45,
              "y":840},
            "size":{
              "width":126,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0563de529bf4fcfa57673c29f7b9f35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'方正舒体 Regular', '方正舒体'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":45,
                  "y":840},
                "size":{
                  "width":126,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5d65581b97614d1bb661790d6bd5e3fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":600,
              "y":745},
            "size":{
              "width":117,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69f9bf189366422c8128f4467c4193b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":600,
                  "y":745},
                "size":{
                  "width":117,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d3511ab1fbb4d129e09633964050ad5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":600,
              "y":802},
            "size":{
              "width":77,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d339bedd5d3408da1f6dec7a384fe6c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":600,
                  "y":802},
                "size":{
                  "width":77,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a283762093604d0dbd2fb47acd755ee0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":693,
              "y":802},
            "size":{
              "width":77,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0780aa133faa4190b3c7928bc592ad89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":693,
                  "y":802},
                "size":{
                  "width":77,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9e1facebec1c4f618afd4c029853d899",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":600,
              "y":841},
            "size":{
              "width":77,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d4046f1a169489bae21e1b3cbd2af84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":600,
                  "y":841},
                "size":{
                  "width":77,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c5dc5062e0354d76ac567a282927a151",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":691,
              "y":841},
            "size":{
              "width":77,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"edc8c25eb889412a82553450e3e8b987",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":691,
                  "y":841},
                "size":{
                  "width":77,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d543d1e8998a4056bb7b6b2121b9bbdb",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":920,
              "y":745},
            "size":{
              "width":117,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"daf30f97e31a40d28d997937c19bfaf9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":920,
                  "y":745},
                "size":{
                  "width":117,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b88b78d50bde411caa160959f2ee2fa9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":920,
              "y":802},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f7f7a9a73c04ae49873ed4341b7dad9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":920,
                  "y":802},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u36.png"}},
{
          "id":"ad353547b5b24c0794cdce2f5f508486",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1000,
              "y":802},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dce0e885e9474b98bae45d1baf92761f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1000,
                  "y":802},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u36.png"}},
{
          "id":"ee10d41d2e2d4975a3e16733f9fa43c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":600,
              "y":200},
            "size":{
              "width":210,
              "height":190}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ababc7d935044f838a35f41fd6ba4247",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":600,
                  "y":200},
                "size":{
                  "width":210,
                  "height":190}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 课件管理页",
                      "target":{
                        "targetType":"page",
                        "url":"课件管理页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登陆后/u8.png"}},
{
          "id":"ddb8d2f30e4d43ada9694a8f4fcb3077",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":874,
              "y":200},
            "size":{
              "width":210,
              "height":190}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1a66c6e90a7482ea59eef1324990d89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":874,
                  "y":200},
                "size":{
                  "width":210,
                  "height":190}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 课件管理页",
                      "target":{
                        "targetType":"page",
                        "url":"课件管理页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登陆后/u8.png"}},
{
          "id":"476ee924001048a69f8ed733cb11dc8b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":330,
              "y":450},
            "size":{
              "width":210,
              "height":190}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b855ad23c9f245d6a4c8e597ade328fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":330,
                  "y":450},
                "size":{
                  "width":210,
                  "height":190}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 课件管理页",
                      "target":{
                        "targetType":"page",
                        "url":"课件管理页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登陆后/u44.png"}},
{
          "id":"b5e2872acdf54808aea17aa39173ef64",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":600,
              "y":450},
            "size":{
              "width":210,
              "height":190}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5be1bbda241246f6bd696c7d06725ef5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":600,
                  "y":450},
                "size":{
                  "width":210,
                  "height":190}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 课件管理页",
                      "target":{
                        "targetType":"page",
                        "url":"课件管理页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登陆后/u44.png"}},
{
          "id":"2496b652d6ba45dcb4d5aa3f02e92965",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":874,
              "y":450},
            "size":{
              "width":210,
              "height":190}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb21638b4ac14f709938a73ec11e92aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":874,
                  "y":450},
                "size":{
                  "width":210,
                  "height":190}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 课件管理页",
                      "target":{
                        "targetType":"page",
                        "url":"课件管理页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登陆后/u44.png"}},
{
          "id":"bdf02b967614496faec2ebd43493d372",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":1134,
              "y":55},
            "size":{
              "width":24,
              "height":18},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eddaa6e4f0874be6b064caf0ddf65112",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":1134,
                  "y":55},
                "size":{
                  "width":24,
                  "height":18},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"切换 set",
                      "objectsToFades":[{
                          "objectPath":["2bca05f1fa1146ab9387e5e039294cef"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登陆后/u50.png"}},
{
          "id":"2bca05f1fa1146ab9387e5e039294cef",
          "label":"set",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":false,
          "style":{
            "location":{
              "x":1127,
              "y":87},
            "size":{
              "width":40,
              "height":61},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ba66a3e9f9b4777a605f6cf648a575c",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":40,
                  "height":61}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"97173be97ac047b8951a739357da6979",
                  "label":"设置与退出",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":40,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a23f96a102224515ae8633394b823c31",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":40,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/登陆后/设置与退出_u54.png"}},
{
                  "id":"a838f5a965ca48d7b7eaed282b41fb7f",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":40,
                      "height":31}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"98aa26c9013a4994b48f8ecc78f41936",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":30},
                        "size":{
                          "width":40,
                          "height":31}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/登陆后/u56.png"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "cee9702b8114490db301dad0b152c3e5":{
      "scriptId":"u0"},
    "95ba5a16870b4b7d90f5ea78fca83930":{
      "scriptId":"u1"},
    "ceee0b478c9f41249ff1553c60d3891c":{
      "scriptId":"u2"},
    "9266f0fb358849138eb8c414c4eb9340":{
      "scriptId":"u3"},
    "3aafc90b25394ddebfdb4e5c3dacdfe0":{
      "scriptId":"u4"},
    "d752c33d6cf7448bbd2d40e3db62043c":{
      "scriptId":"u5"},
    "5697bdf14e784e0b85c3cf25540cb926":{
      "scriptId":"u6"},
    "854d9f202666406eae02fa1d6cd2956c":{
      "scriptId":"u7"},
    "4ec2a28c56044b95afcbe68300e0cc01":{
      "scriptId":"u8"},
    "380164424ab14d7eb1687bcbf2ee37a1":{
      "scriptId":"u9"},
    "8875444e949f418a997649aab224d32a":{
      "scriptId":"u10"},
    "dc888f0e74fa4a2e8066c0f73324677a":{
      "scriptId":"u11"},
    "87900c0749e1435b965e376e2fdc698b":{
      "scriptId":"u12"},
    "5f21cc9e13fb41db9562c0614754f2d5":{
      "scriptId":"u13"},
    "807ac0b1cac84f60b78ba0d78e674ce7":{
      "scriptId":"u14"},
    "24626b8f8f0843488c40514ca15e7acb":{
      "scriptId":"u15"},
    "1f3573a1494c4c4dab4430742ea0554f":{
      "scriptId":"u16"},
    "f2d4cfb5282f4516aa2318ce3f95feb7":{
      "scriptId":"u17"},
    "c6e5957439da478cb06cb207ab08a2f9":{
      "scriptId":"u18"},
    "be0b974592744b6687d8e8a0ec90f3d8":{
      "scriptId":"u19"},
    "25fa01ebd81f4c2fbc518ceaf82fab1e":{
      "scriptId":"u20"},
    "0dd26fb92426421da65e6e77467a0109":{
      "scriptId":"u21"},
    "2bd35ce570274e99823383d77cd89faf":{
      "scriptId":"u22"},
    "f0563de529bf4fcfa57673c29f7b9f35":{
      "scriptId":"u23"},
    "5d65581b97614d1bb661790d6bd5e3fb":{
      "scriptId":"u24"},
    "69f9bf189366422c8128f4467c4193b6":{
      "scriptId":"u25"},
    "4d3511ab1fbb4d129e09633964050ad5":{
      "scriptId":"u26"},
    "9d339bedd5d3408da1f6dec7a384fe6c":{
      "scriptId":"u27"},
    "a283762093604d0dbd2fb47acd755ee0":{
      "scriptId":"u28"},
    "0780aa133faa4190b3c7928bc592ad89":{
      "scriptId":"u29"},
    "9e1facebec1c4f618afd4c029853d899":{
      "scriptId":"u30"},
    "4d4046f1a169489bae21e1b3cbd2af84":{
      "scriptId":"u31"},
    "c5dc5062e0354d76ac567a282927a151":{
      "scriptId":"u32"},
    "edc8c25eb889412a82553450e3e8b987":{
      "scriptId":"u33"},
    "d543d1e8998a4056bb7b6b2121b9bbdb":{
      "scriptId":"u34"},
    "daf30f97e31a40d28d997937c19bfaf9":{
      "scriptId":"u35"},
    "b88b78d50bde411caa160959f2ee2fa9":{
      "scriptId":"u36"},
    "9f7f7a9a73c04ae49873ed4341b7dad9":{
      "scriptId":"u37"},
    "ad353547b5b24c0794cdce2f5f508486":{
      "scriptId":"u38"},
    "dce0e885e9474b98bae45d1baf92761f":{
      "scriptId":"u39"},
    "ee10d41d2e2d4975a3e16733f9fa43c9":{
      "scriptId":"u40"},
    "ababc7d935044f838a35f41fd6ba4247":{
      "scriptId":"u41"},
    "ddb8d2f30e4d43ada9694a8f4fcb3077":{
      "scriptId":"u42"},
    "a1a66c6e90a7482ea59eef1324990d89":{
      "scriptId":"u43"},
    "476ee924001048a69f8ed733cb11dc8b":{
      "scriptId":"u44"},
    "b855ad23c9f245d6a4c8e597ade328fd":{
      "scriptId":"u45"},
    "b5e2872acdf54808aea17aa39173ef64":{
      "scriptId":"u46"},
    "5be1bbda241246f6bd696c7d06725ef5":{
      "scriptId":"u47"},
    "2496b652d6ba45dcb4d5aa3f02e92965":{
      "scriptId":"u48"},
    "cb21638b4ac14f709938a73ec11e92aa":{
      "scriptId":"u49"},
    "bdf02b967614496faec2ebd43493d372":{
      "scriptId":"u50"},
    "eddaa6e4f0874be6b064caf0ddf65112":{
      "scriptId":"u51"},
    "2bca05f1fa1146ab9387e5e039294cef":{
      "scriptId":"u52"},
    "4ba66a3e9f9b4777a605f6cf648a575c":{
      "scriptId":"u53"},
    "97173be97ac047b8951a739357da6979":{
      "scriptId":"u54"},
    "a23f96a102224515ae8633394b823c31":{
      "scriptId":"u55"},
    "a838f5a965ca48d7b7eaed282b41fb7f":{
      "scriptId":"u56"},
    "98aa26c9013a4994b48f8ecc78f41936":{
      "scriptId":"u57"}}});