$axure.loadCurrentPage({
  "url":"课堂检测管理页.html",
  "generationDate":new Date(1491295963193.14),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"79a3ea6368a84298b4f293c9596feaef",
    "type":"Axure:Page",
    "name":"课堂检测管理页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d56dabbe39d042d18636e2490f2208f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "size":{
              "width":1200,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5fe976111ad54bafa9ff3fa6cc625198",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "size":{
                  "width":1200,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u0.png"}},
{
          "id":"188a7c03e2654626b5cc729d990f1657",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":27,
              "y":0},
            "size":{
              "width":202,
              "height":118}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9853669052d34b128e424f7fef459475",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":27,
                  "y":0},
                "size":{
                  "width":202,
                  "height":118}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登陆后",
                      "target":{
                        "targetType":"page",
                        "url":"登陆后.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8de323f6309a4ca394c4c485547fa7ec",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1051,
              "y":20},
            "size":{
              "width":80,
              "height":80},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"100"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"106d639be2f34251be5f1ada6cae208e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1051,
                  "y":20},
                "size":{
                  "width":80,
                  "height":80},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"100"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u4.png"}},
{
          "id":"1e2b2eb3a4cf4b80b64ec761030d7e08",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":0,
              "y":130},
            "size":{
              "width":230,
              "height":590}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b89a7dabbba430db3cb75fac12b946d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":0,
                  "y":130},
                "size":{
                  "width":230,
                  "height":590}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u6.png"}},
{
          "id":"9d6bc01fc0a449f5a55c2708827516ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":213},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b6eb39d7a934cd8bc5136a2389c9c19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":213},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登陆后",
                      "target":{
                        "targetType":"page",
                        "url":"登陆后.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6e2910ee19db4b1fa1ce27f5ffc22914",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":308},
            "size":{
              "width":97,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"783277eb00f44227bac3809c11ae38f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":308},
                "size":{
                  "width":97,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 公告栏主页面",
                      "target":{
                        "targetType":"page",
                        "url":"公告栏主页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7d33d571fd1c4451a9baeceab683eaf7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":400},
            "size":{
              "width":97,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6f4bece126144128a153e1fbbda2888",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":400},
                "size":{
                  "width":97,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 讨论区主页面",
                      "target":{
                        "targetType":"page",
                        "url":"讨论区主页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"65ef7ab16f6447ff9cf930a224d0cb95",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":490},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6074223e26964eb383e50f41bbe2a77a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":490},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 成绩管理主页面",
                      "target":{
                        "targetType":"page",
                        "url":"成绩管理主页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"387ce0f32d7740cda386fbf36128da35",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF363636},
            "location":{
              "x":0,
              "y":720},
            "size":{
              "width":1200,
              "height":180}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d1a096b9aaa4426b917bedb73773ab0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF363636},
                "location":{
                  "x":0,
                  "y":720},
                "size":{
                  "width":1200,
                  "height":180}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u18.png"}},
{
          "id":"1a54c3f0af53494fadddbe3850af7aef",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":59,
              "y":745},
            "size":{
              "width":87,
              "height":85}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ca95d456878446ba194c30c1aa36098",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":59,
                  "y":745},
                "size":{
                  "width":87,
                  "height":85}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u20.jpg"}},
{
          "id":"1dc3ebe9e1464c9696562aed7a0fead6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'方正舒体 Regular', '方正舒体'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":45,
              "y":840},
            "size":{
              "width":126,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"375a434e331d41af958832a17297ed98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'方正舒体 Regular', '方正舒体'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":45,
                  "y":840},
                "size":{
                  "width":126,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"941c1339054d4c4285fc200ccb068208",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":600,
              "y":745},
            "size":{
              "width":117,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4264e50492742c3a2f409d9e8098704",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":600,
                  "y":745},
                "size":{
                  "width":117,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"937e88c2f5c54e22a99d15cbf627c02d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":600,
              "y":802},
            "size":{
              "width":77,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2b1921693104909b4991be3660e6c17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":600,
                  "y":802},
                "size":{
                  "width":77,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9aaf932bcad34245a94a5e88626328f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":693,
              "y":802},
            "size":{
              "width":77,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0cecf3e8913c4667ba3f2971c6823958",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":693,
                  "y":802},
                "size":{
                  "width":77,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c8a07d8dc7ac4f0c8389ef51d2f6d499",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":600,
              "y":841},
            "size":{
              "width":77,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4972847206a4f4d9dbe8f3b97a83199",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":600,
                  "y":841},
                "size":{
                  "width":77,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"667ea9ec6ffb40faacfa2fdd0d1cc81e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":691,
              "y":841},
            "size":{
              "width":77,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d8794aeb7ab484b992d8ffc95e759c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":691,
                  "y":841},
                "size":{
                  "width":77,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9b1b6ff34502461abc7798992ef662bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":920,
              "y":745},
            "size":{
              "width":117,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1cf06b728a1d4f9dbdac23a89f957e86",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":920,
                  "y":745},
                "size":{
                  "width":117,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"17c8578f6c6844ebb7b33351dca18e8a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":920,
              "y":802},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eab28e2d48ed4ff1bfcd43452708f70d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":920,
                  "y":802},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u36.png"}},
{
          "id":"4dc5c86016fa41558c6812023fff498c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1000,
              "y":802},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a25c5f219514408be682ec7372f0491",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1000,
                  "y":802},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u36.png"}},
{
          "id":"c3cf9f5aac4d4b49a877f7072d0e6e8f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":206},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7481b1487e3b44ac981df7f63baf075e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":206},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f787c061e2314489b2e470598b93ac87",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Gill Sans Ultra Bold', 'Gill Sans'",
            "fontSize":"36px",
            "fontWeight":"800",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF66FF66},
            "location":{
              "x":419,
              "y":209.5},
            "size":{
              "width":30,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02768d6f6461455288226463917fdfcd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Gill Sans Ultra Bold', 'Gill Sans'",
                "fontSize":"36px",
                "fontWeight":"800",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF66FF66},
                "location":{
                  "x":419,
                  "y":209.5},
                "size":{
                  "width":30,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/课件管理页/u72.png"}},
{
          "id":"cef59dc92fa142c795449657c6cce434",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":280},
            "size":{
              "width":860,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a64fd1d5e3f94ab6ac3780aa39ad15fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":280},
                "size":{
                  "width":860,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/课堂检测管理页/u42.png"}},
{
          "id":"67153002e51d4bb498e014ed0077d3be",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":294,
              "y":290},
            "size":{
              "width":121,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11ddf169a3a046c0b13d361cc3def83d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":294,
                  "y":290},
                "size":{
                  "width":121,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 某次测试页",
                      "target":{
                        "targetType":"page",
                        "url":"某次测试页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9a713d64122745e7ac51e296c0eed066",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":294,
              "y":328},
            "size":{
              "width":826,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27da101aa3914cf091b5635e283f3123",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":294,
                  "y":328},
                "size":{
                  "width":826,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/课堂检测管理页/u46.png"}},
{
          "id":"8821baf9ebca45b1850976edff5d28c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":1014,
              "y":290},
            "size":{
              "width":106,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4d1f72620c54c3d9303c8f77e719c1d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":1014,
                  "y":290},
                "size":{
                  "width":106,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"80b73dd18ba34392b738e3cffaff02c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":420},
            "size":{
              "width":860,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51028f8aedc4407eaba96d7613c507ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":420},
                "size":{
                  "width":860,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/课堂检测管理页/u42.png"}},
{
          "id":"2ca07e54c7a2440c85d6fdccede9c0b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":294,
              "y":431},
            "size":{
              "width":121,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b291ba95a29470ba3dab94c40627f8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":294,
                  "y":431},
                "size":{
                  "width":121,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4a41d2a38f28498f83848ac5509321a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":294,
              "y":468},
            "size":{
              "width":826,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6c20651e35a43938288efd45569e3b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":294,
                  "y":468},
                "size":{
                  "width":826,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/课堂检测管理页/u46.png"}},
{
          "id":"de50b9262064476fadaddb1f77b04067",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":1014,
              "y":420},
            "size":{
              "width":106,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d05a52dd80547a799584b38b0811e7d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":1014,
                  "y":420},
                "size":{
                  "width":106,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cd78e1c070f94491ae2c7abac7cb5c39",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":560},
            "size":{
              "width":860,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b44fa1dfd5f44cfbcfff3df9d4b515a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":560},
                "size":{
                  "width":860,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/课堂检测管理页/u42.png"}},
{
          "id":"99ff4b16e3674e8682d81e4bf331e12b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":294,
              "y":570},
            "size":{
              "width":121,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f492b6d113c469bb0a685adfc557fad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":294,
                  "y":570},
                "size":{
                  "width":121,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"28963f708bf34cfcbeadb63493a22a0b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":294,
              "y":608},
            "size":{
              "width":826,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"deb735a1ae20457aa45c4c241da42a88",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":294,
                  "y":608},
                "size":{
                  "width":826,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/课堂检测管理页/u46.png"}},
{
          "id":"74b746de269b4ef688b00126251ee3d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":1014,
              "y":570},
            "size":{
              "width":106,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45305b7db43c4bc688920a86a04f7055",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":1014,
                  "y":570},
                "size":{
                  "width":106,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2a9ed5a89541449a8653a52a21373cf9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":1134,
              "y":55},
            "size":{
              "width":24,
              "height":18},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4d90ad1cb414f09b472897e22c559a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":1134,
                  "y":55},
                "size":{
                  "width":24,
                  "height":18},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"切换 set",
                      "objectsToFades":[{
                          "objectPath":["6cf004b5008a45ffac8d25c413ff6bd1"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登陆后/u50.png"}},
{
          "id":"6cf004b5008a45ffac8d25c413ff6bd1",
          "label":"set",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":false,
          "style":{
            "location":{
              "x":1127,
              "y":87},
            "size":{
              "width":40,
              "height":61},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5311c034cf824db99658786fe2ef55f0",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":40,
                  "height":61}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1d4e659ee5094c06b7ef7518448d88b5",
                  "label":"设置与退出",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":40,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c59a7d6fdf554b85bbd3feda7fd957e9",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":40,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/登陆后/设置与退出_u54.png"}},
{
                  "id":"12d7fd1217284637ac89e8446f1e9cec",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":40,
                      "height":31}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d8c01b23ae3043c99506506c2788f8ee",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":30},
                        "size":{
                          "width":40,
                          "height":31}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/登陆后/u56.png"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "d56dabbe39d042d18636e2490f2208f0":{
      "scriptId":"u0"},
    "5fe976111ad54bafa9ff3fa6cc625198":{
      "scriptId":"u1"},
    "188a7c03e2654626b5cc729d990f1657":{
      "scriptId":"u2"},
    "9853669052d34b128e424f7fef459475":{
      "scriptId":"u3"},
    "8de323f6309a4ca394c4c485547fa7ec":{
      "scriptId":"u4"},
    "106d639be2f34251be5f1ada6cae208e":{
      "scriptId":"u5"},
    "1e2b2eb3a4cf4b80b64ec761030d7e08":{
      "scriptId":"u6"},
    "4b89a7dabbba430db3cb75fac12b946d":{
      "scriptId":"u7"},
    "9d6bc01fc0a449f5a55c2708827516ea":{
      "scriptId":"u8"},
    "5b6eb39d7a934cd8bc5136a2389c9c19":{
      "scriptId":"u9"},
    "6e2910ee19db4b1fa1ce27f5ffc22914":{
      "scriptId":"u10"},
    "783277eb00f44227bac3809c11ae38f0":{
      "scriptId":"u11"},
    "7d33d571fd1c4451a9baeceab683eaf7":{
      "scriptId":"u12"},
    "f6f4bece126144128a153e1fbbda2888":{
      "scriptId":"u13"},
    "65ef7ab16f6447ff9cf930a224d0cb95":{
      "scriptId":"u14"},
    "6074223e26964eb383e50f41bbe2a77a":{
      "scriptId":"u15"},
    "387ce0f32d7740cda386fbf36128da35":{
      "scriptId":"u16"},
    "6d1a096b9aaa4426b917bedb73773ab0":{
      "scriptId":"u17"},
    "1a54c3f0af53494fadddbe3850af7aef":{
      "scriptId":"u18"},
    "4ca95d456878446ba194c30c1aa36098":{
      "scriptId":"u19"},
    "1dc3ebe9e1464c9696562aed7a0fead6":{
      "scriptId":"u20"},
    "375a434e331d41af958832a17297ed98":{
      "scriptId":"u21"},
    "941c1339054d4c4285fc200ccb068208":{
      "scriptId":"u22"},
    "d4264e50492742c3a2f409d9e8098704":{
      "scriptId":"u23"},
    "937e88c2f5c54e22a99d15cbf627c02d":{
      "scriptId":"u24"},
    "c2b1921693104909b4991be3660e6c17":{
      "scriptId":"u25"},
    "9aaf932bcad34245a94a5e88626328f6":{
      "scriptId":"u26"},
    "0cecf3e8913c4667ba3f2971c6823958":{
      "scriptId":"u27"},
    "c8a07d8dc7ac4f0c8389ef51d2f6d499":{
      "scriptId":"u28"},
    "a4972847206a4f4d9dbe8f3b97a83199":{
      "scriptId":"u29"},
    "667ea9ec6ffb40faacfa2fdd0d1cc81e":{
      "scriptId":"u30"},
    "4d8794aeb7ab484b992d8ffc95e759c0":{
      "scriptId":"u31"},
    "9b1b6ff34502461abc7798992ef662bd":{
      "scriptId":"u32"},
    "1cf06b728a1d4f9dbdac23a89f957e86":{
      "scriptId":"u33"},
    "17c8578f6c6844ebb7b33351dca18e8a":{
      "scriptId":"u34"},
    "eab28e2d48ed4ff1bfcd43452708f70d":{
      "scriptId":"u35"},
    "4dc5c86016fa41558c6812023fff498c":{
      "scriptId":"u36"},
    "1a25c5f219514408be682ec7372f0491":{
      "scriptId":"u37"},
    "c3cf9f5aac4d4b49a877f7072d0e6e8f":{
      "scriptId":"u38"},
    "7481b1487e3b44ac981df7f63baf075e":{
      "scriptId":"u39"},
    "f787c061e2314489b2e470598b93ac87":{
      "scriptId":"u40"},
    "02768d6f6461455288226463917fdfcd":{
      "scriptId":"u41"},
    "cef59dc92fa142c795449657c6cce434":{
      "scriptId":"u42"},
    "a64fd1d5e3f94ab6ac3780aa39ad15fd":{
      "scriptId":"u43"},
    "67153002e51d4bb498e014ed0077d3be":{
      "scriptId":"u44"},
    "11ddf169a3a046c0b13d361cc3def83d":{
      "scriptId":"u45"},
    "9a713d64122745e7ac51e296c0eed066":{
      "scriptId":"u46"},
    "27da101aa3914cf091b5635e283f3123":{
      "scriptId":"u47"},
    "8821baf9ebca45b1850976edff5d28c4":{
      "scriptId":"u48"},
    "a4d1f72620c54c3d9303c8f77e719c1d":{
      "scriptId":"u49"},
    "80b73dd18ba34392b738e3cffaff02c6":{
      "scriptId":"u50"},
    "51028f8aedc4407eaba96d7613c507ba":{
      "scriptId":"u51"},
    "2ca07e54c7a2440c85d6fdccede9c0b5":{
      "scriptId":"u52"},
    "5b291ba95a29470ba3dab94c40627f8b":{
      "scriptId":"u53"},
    "4a41d2a38f28498f83848ac5509321a2":{
      "scriptId":"u54"},
    "a6c20651e35a43938288efd45569e3b2":{
      "scriptId":"u55"},
    "de50b9262064476fadaddb1f77b04067":{
      "scriptId":"u56"},
    "7d05a52dd80547a799584b38b0811e7d":{
      "scriptId":"u57"},
    "cd78e1c070f94491ae2c7abac7cb5c39":{
      "scriptId":"u58"},
    "7b44fa1dfd5f44cfbcfff3df9d4b515a":{
      "scriptId":"u59"},
    "99ff4b16e3674e8682d81e4bf331e12b":{
      "scriptId":"u60"},
    "4f492b6d113c469bb0a685adfc557fad":{
      "scriptId":"u61"},
    "28963f708bf34cfcbeadb63493a22a0b":{
      "scriptId":"u62"},
    "deb735a1ae20457aa45c4c241da42a88":{
      "scriptId":"u63"},
    "74b746de269b4ef688b00126251ee3d5":{
      "scriptId":"u64"},
    "45305b7db43c4bc688920a86a04f7055":{
      "scriptId":"u65"},
    "2a9ed5a89541449a8653a52a21373cf9":{
      "scriptId":"u66"},
    "c4d90ad1cb414f09b472897e22c559a7":{
      "scriptId":"u67"},
    "6cf004b5008a45ffac8d25c413ff6bd1":{
      "scriptId":"u68"},
    "5311c034cf824db99658786fe2ef55f0":{
      "scriptId":"u69"},
    "1d4e659ee5094c06b7ef7518448d88b5":{
      "scriptId":"u70"},
    "c59a7d6fdf554b85bbd3feda7fd957e9":{
      "scriptId":"u71"},
    "12d7fd1217284637ac89e8446f1e9cec":{
      "scriptId":"u72"},
    "d8c01b23ae3043c99506506c2788f8ee":{
      "scriptId":"u73"}}});