$axure.loadCurrentPage({
  "url":"登录前.html",
  "generationDate":new Date(1491295962573.87),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"66ccaf2ac7614f788fa967585c2eba8a",
    "type":"Axure:Page",
    "name":"登录前",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"center",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c31ef6e469c54c9ebb0e1229f9d91149",
          "label":"登陆框",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":403,
              "y":140},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onLoad":{
              "description":"OnLoad",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 登陆框 灯箱效果",
                      "objectsToFades":[{
                          "objectPath":["c31ef6e469c54c9ebb0e1229f9d91149"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"lightbox",
                              "lightbox":{
                                "r":228,
                                "g":228,
                                "b":228,
                                "a":155}}}}]}]}]}},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"e2b85d339bee4fc695e16543a2f1f78f",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"22a46aa2bc104c45a472c322900cc5ad",
                  "label":"",
                  "parentDynamicPanel":"c31ef6e469c54c9ebb0e1229f9d91149",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0099FF},
                    "size":{
                      "width":390,
                      "height":490},
                    "outerShadow":{
                      "on":true,
                      "offsetX":5,
                      "offsetY":5,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"daf7a27cfd1e42ec8aebab0340addfa7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c31ef6e469c54c9ebb0e1229f9d91149",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF0099FF},
                        "size":{
                          "width":390,
                          "height":490},
                        "outerShadow":{
                          "on":true,
                          "offsetX":5,
                          "offsetY":5,
                          "blurRadius":5,
                          "color":{
                            "r":0,
                            "g":0,
                            "b":0,
                            "a":0.349019607843137}}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/登录前/u1.png"}},
{
                  "id":"1690bcbc05ca4b649c40f719eee9e3ad",
                  "label":"",
                  "parentDynamicPanel":"c31ef6e469c54c9ebb0e1229f9d91149",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "fontSize":"18px",
                    "location":{
                      "x":65,
                      "y":182},
                    "size":{
                      "width":260,
                      "height":49}},
                  "adaptiveStyles":{
},
                  "placeholderText":"请输入教务系统帐号"},
{
                  "id":"18f4b30e1155485c9196dccf08479315",
                  "label":"",
                  "parentDynamicPanel":"c31ef6e469c54c9ebb0e1229f9d91149",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "fontSize":"18px",
                    "location":{
                      "x":65,
                      "y":268},
                    "size":{
                      "width":260,
                      "height":49}},
                  "adaptiveStyles":{
},
                  "placeholderText":"请输入教务系统密码"},
{
                  "id":"8b9175d11f76451fbce94ac1c58049a8",
                  "label":"",
                  "parentDynamicPanel":"c31ef6e469c54c9ebb0e1229f9d91149",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"28px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF282828},
                    "location":{
                      "x":65,
                      "y":373},
                    "size":{
                      "width":260,
                      "height":62},
                    "cornerRadiusTopLeft":"5",
                    "outerShadow":{
                      "on":true,
                      "offsetX":5,
                      "offsetY":5,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3b6be707d98843f394bbfe37d91bf6bd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c31ef6e469c54c9ebb0e1229f9d91149",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"28px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF282828},
                        "location":{
                          "x":65,
                          "y":373},
                        "size":{
                          "width":260,
                          "height":62},
                        "cornerRadiusTopLeft":"5",
                        "outerShadow":{
                          "on":true,
                          "offsetX":5,
                          "offsetY":5,
                          "blurRadius":5,
                          "color":{
                            "r":0,
                            "g":0,
                            "b":0,
                            "a":0.349019607843137}}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 登陆后",
                              "target":{
                                "targetType":"page",
                                "url":"登陆后.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/登录前/u5.png"}},
{
                  "id":"832e7c055d3245b9b7680869d32fe7ed",
                  "label":"",
                  "parentDynamicPanel":"c31ef6e469c54c9ebb0e1229f9d91149",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":34,
                      "y":13},
                    "size":{
                      "width":322,
                      "height":118}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9d3128f2ae774cfd9df9ab179030b07f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c31ef6e469c54c9ebb0e1229f9d91149",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":34,
                          "y":13},
                        "size":{
                          "width":322,
                          "height":118}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "c31ef6e469c54c9ebb0e1229f9d91149":{
      "scriptId":"u0"},
    "22a46aa2bc104c45a472c322900cc5ad":{
      "scriptId":"u1"},
    "daf7a27cfd1e42ec8aebab0340addfa7":{
      "scriptId":"u2"},
    "1690bcbc05ca4b649c40f719eee9e3ad":{
      "scriptId":"u3"},
    "18f4b30e1155485c9196dccf08479315":{
      "scriptId":"u4"},
    "8b9175d11f76451fbce94ac1c58049a8":{
      "scriptId":"u5"},
    "3b6be707d98843f394bbfe37d91bf6bd":{
      "scriptId":"u6"},
    "832e7c055d3245b9b7680869d32fe7ed":{
      "scriptId":"u7"},
    "9d3128f2ae774cfd9df9ab179030b07f":{
      "scriptId":"u8"}}});