$axure.loadCurrentPage({
  "url":"某一课程页.html",
  "generationDate":new Date(1491295964684.47),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b55b0ed0ade0489b9918cfe20fa5ff52",
    "type":"Axure:Page",
    "name":"某一课程页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5bc0bc7e763047a1b4d9287d5a31fe5e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "size":{
              "width":1200,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25f1e73eb8cd40f3afcfdee6cfda75d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "size":{
                  "width":1200,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u0.png"}},
{
          "id":"38fc6c7315124635ab5202f5d2d4807b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":27,
              "y":0},
            "size":{
              "width":202,
              "height":118}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7404297938b4964ac349b772f2dd45d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":27,
                  "y":0},
                "size":{
                  "width":202,
                  "height":118}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登陆后",
                      "target":{
                        "targetType":"page",
                        "url":"登陆后.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9ab3882eb150499ba9a3482caa7ba0ce",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1051,
              "y":20},
            "size":{
              "width":80,
              "height":80},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"100"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b329ddef22554ac08aa8e34a843fd3f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1051,
                  "y":20},
                "size":{
                  "width":80,
                  "height":80},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"100"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u4.png"}},
{
          "id":"802c576f5e4a4e698ec0a07e2e48523e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":0,
              "y":130},
            "size":{
              "width":230,
              "height":590}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c47d198588640248a798ce961c08244",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":0,
                  "y":130},
                "size":{
                  "width":230,
                  "height":590}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u6.png"}},
{
          "id":"907a58fb91b94e65bf925dc4f9e190ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":213},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c116158ecc1a4df6b6d69eb1ce3abc36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":213},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登陆后",
                      "target":{
                        "targetType":"page",
                        "url":"登陆后.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"14271d4d10e44024acfb7bc60518c238",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":308},
            "size":{
              "width":97,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72abbb1b1f604ee8b2c3e276de2b731d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":308},
                "size":{
                  "width":97,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 公告栏主页面",
                      "target":{
                        "targetType":"page",
                        "url":"公告栏主页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bc0e372fff7548f594bc0877694fd156",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":400},
            "size":{
              "width":97,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52135b265a884575ae507ba0662bc1e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":400},
                "size":{
                  "width":97,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 讨论区主页面",
                      "target":{
                        "targetType":"page",
                        "url":"讨论区主页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"098730e012bc4e3787b7ef68a4b7b512",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":490},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a45979220494000963df10c494e73da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":490},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 成绩管理主页面",
                      "target":{
                        "targetType":"page",
                        "url":"成绩管理主页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9194cb3781b5422b87df7386afe0de79",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF363636},
            "location":{
              "x":0,
              "y":720},
            "size":{
              "width":1200,
              "height":180}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0c709214a734e52ac93eac6ff2074bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF363636},
                "location":{
                  "x":0,
                  "y":720},
                "size":{
                  "width":1200,
                  "height":180}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u18.png"}},
{
          "id":"398bcfd24c4447d5b688e668a8e5d1ff",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":59,
              "y":745},
            "size":{
              "width":87,
              "height":85}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fdda9f806b774ef99cf0a63323b1aa9f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":59,
                  "y":745},
                "size":{
                  "width":87,
                  "height":85}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u20.jpg"}},
{
          "id":"2928db9f032249749b558926e805ce69",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'方正舒体 Regular', '方正舒体'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":45,
              "y":840},
            "size":{
              "width":126,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1b928471cb74ba38b3fda24783f11fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'方正舒体 Regular', '方正舒体'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":45,
                  "y":840},
                "size":{
                  "width":126,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a774a77880c443749cda7626ef230227",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":600,
              "y":745},
            "size":{
              "width":117,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44e832ed0f5b4d3fb3798c4bc6fe6681",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":600,
                  "y":745},
                "size":{
                  "width":117,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"00796e32090c4c66854f675ab8041ce5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":600,
              "y":802},
            "size":{
              "width":77,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf16a4b1aad642c4b964832654edcdce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":600,
                  "y":802},
                "size":{
                  "width":77,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ab8f6640b11e42708b3eae01ae0deca7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":693,
              "y":802},
            "size":{
              "width":77,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1cb71bb5c5d54d9994f1f42aea869f51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":693,
                  "y":802},
                "size":{
                  "width":77,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1d64add7969d471a8d7a5d0c2b466f99",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":600,
              "y":841},
            "size":{
              "width":77,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5fcd7081edd0452585f411c02f349153",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":600,
                  "y":841},
                "size":{
                  "width":77,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ce27abb791c34312b9ca1b1f6895c0d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":691,
              "y":841},
            "size":{
              "width":77,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1b7cac832b84189a1ea47b941f63a28",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":691,
                  "y":841},
                "size":{
                  "width":77,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"40af750d171b495392915519647741e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":920,
              "y":745},
            "size":{
              "width":117,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06f370825f394d208cc93c5e57b99fe3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":920,
                  "y":745},
                "size":{
                  "width":117,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"05c6267ff3814ce6827b0297d3a1ac60",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":920,
              "y":802},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8fa94ce70b0d4cac84f560beb16755c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":920,
                  "y":802},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u36.png"}},
{
          "id":"d627e9645b0f43759031897ae3f83d4d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1000,
              "y":802},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8617a5f5c0e64190b796c354d19c7a6a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1000,
                  "y":802},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u36.png"}},
{
          "id":"9f04f101ce82472a9487099ac43e0a60",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":1134,
              "y":55},
            "size":{
              "width":24,
              "height":18},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbe9725e1cbc487b8bbefe39480f52df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":1134,
                  "y":55},
                "size":{
                  "width":24,
                  "height":18},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"切换 set",
                      "objectsToFades":[{
                          "objectPath":["d67fd0664cb94f009709f22152c289eb"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登陆后/u50.png"}},
{
          "id":"d67fd0664cb94f009709f22152c289eb",
          "label":"set",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":false,
          "style":{
            "location":{
              "x":1127,
              "y":87},
            "size":{
              "width":40,
              "height":61},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57bcc3c2277a4aa59f1cb94e7a471b6f",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":40,
                  "height":61}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7e379b95fad44f69b40d94cadccd69f0",
                  "label":"设置与退出",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":40,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dad536c5f08f43f29c9eaed5a4348d02",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":40,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/登陆后/设置与退出_u54.png"}},
{
                  "id":"a9b02659625441cb9d200e7ba3a0ebb6",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":40,
                      "height":31}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2e0a5e6ea1b74416aea0c395b60425b6",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":30},
                        "size":{
                          "width":40,
                          "height":31}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/登陆后/u56.png"}}]}]},
{
          "id":"f349d188d65346229c96f4da9c978e01",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":260},
            "size":{
              "width":898,
              "height":360}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a60c80525591451cbdeaba138f282d2e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":299,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0dbf9bb501624cbfa2b7f437d795dbd2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":299,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某一课程页/u47.png"}},
{
              "id":"aa36416ee17642998a1f4c2ae5c0f9f4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":299,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"603a2c02536048c78273a249183dd59d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":299,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某一课程页/u47.png"}},
{
              "id":"2f392f5e7cc741dbb0bef9ac9f02aafa",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":299,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3f686081ed024bffb77c5a3d6c434505",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":299,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某一课程页/u47.png"}},
{
              "id":"071ab031cb444fcb945a4b7c2bc41cee",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":299,
                  "y":0},
                "size":{
                  "width":299,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9bbda4428d944d278ea33d2677a46505",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":299,
                      "y":0},
                    "size":{
                      "width":299,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某一课程页/u47.png"}},
{
              "id":"865824b5921649b0b06dd999fc882cb2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":299,
                  "y":30},
                "size":{
                  "width":299,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"846e95087d014b85a361fddaee2e711d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":299,
                      "y":30},
                    "size":{
                      "width":299,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某一课程页/u47.png"}},
{
              "id":"bba3868152b84c3ea36a664bc436ba65",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":299,
                  "y":60},
                "size":{
                  "width":299,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"acd130535efe48218ea2090d65fd4977",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":299,
                      "y":60},
                    "size":{
                      "width":299,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某一课程页/u47.png"}},
{
              "id":"d1b70b4fc3eb4fa7ae78c9e19009f24a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":598,
                  "y":0},
                "size":{
                  "width":300,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cead48be7d464037bf104566cf2e5825",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":598,
                      "y":0},
                    "size":{
                      "width":300,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某一课程页/u51.png"}},
{
              "id":"a6144fb3f8ab4f52ad66d305feed9e12",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":598,
                  "y":30},
                "size":{
                  "width":300,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dc696d76b5c7467382b9c8dfe45a55e0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":598,
                      "y":30},
                    "size":{
                      "width":300,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某一课程页/u51.png"}},
{
              "id":"88a0e7f7e1d74896b4b61d61ac8b11d2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":598,
                  "y":60},
                "size":{
                  "width":300,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b3b719e07c844ef881450b8b43f58d8c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":598,
                      "y":60},
                    "size":{
                      "width":300,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某一课程页/u51.png"}},
{
              "id":"b5e5e8241ba04dc691f2158c4b2f5b17",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":90},
                "size":{
                  "width":299,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b04a3a6807e04d05b8c38056bca2fe2a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":90},
                    "size":{
                      "width":299,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某一课程页/u47.png"}},
{
              "id":"491db4242652492ab4673873c044e469",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":299,
                  "y":90},
                "size":{
                  "width":299,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"968308bdce454a97892e5fdc53615290",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":299,
                      "y":90},
                    "size":{
                      "width":299,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某一课程页/u47.png"}},
{
              "id":"23840b16e3a947188c6167233b99a8de",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":598,
                  "y":90},
                "size":{
                  "width":300,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"83f024f8146c4019ad25378176c46f6e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":598,
                      "y":90},
                    "size":{
                      "width":300,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某一课程页/u51.png"}},
{
              "id":"89dc29c161324de9ad1d9caf398f1610",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":120},
                "size":{
                  "width":299,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8b7a4b69301f4e22b60e6dfcebc48d64",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":120},
                    "size":{
                      "width":299,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某一课程页/u47.png"}},
{
              "id":"917c40f20ed340879ad48d80cdc02580",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":299,
                  "y":120},
                "size":{
                  "width":299,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"85f39b8b136745b19badb1b31a394f28",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":299,
                      "y":120},
                    "size":{
                      "width":299,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某一课程页/u47.png"}},
{
              "id":"3c5c3c6a011f4a198bb1b8532d402c87",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":598,
                  "y":120},
                "size":{
                  "width":300,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6def6653c2ba4c03a779150880272239",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":598,
                      "y":120},
                    "size":{
                      "width":300,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某一课程页/u51.png"}},
{
              "id":"699e7a22e60048198a5ca2420b4dd15f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":330},
                "size":{
                  "width":299,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6150ddb63dfa4e65a3bc73923c34263f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":330},
                    "size":{
                      "width":299,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某一课程页/u113.png"}},
{
              "id":"7239a769df734d93a6cd3a112ba9b0db",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":299,
                  "y":330},
                "size":{
                  "width":299,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b3ccb723c21144078f68a6b4370227e1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":299,
                      "y":330},
                    "size":{
                      "width":299,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某一课程页/u113.png"}},
{
              "id":"9d9a102e42b54b90bbec225445e7ca16",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":598,
                  "y":330},
                "size":{
                  "width":300,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2f29073beee54726a89e5c444b442dc3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":598,
                      "y":330},
                    "size":{
                      "width":300,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某一课程页/u117.png"}},
{
              "id":"6456406a43264ca9b96204a7ae79d126",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":150},
                "size":{
                  "width":299,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a2ead798cf304c48bb92c32f0d16c66b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":150},
                    "size":{
                      "width":299,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某一课程页/u47.png"}},
{
              "id":"80386216ccb046baa0cf1d7fc17913b7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":299,
                  "y":150},
                "size":{
                  "width":299,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"12d133b903884bb5923ac065d3089af4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":299,
                      "y":150},
                    "size":{
                      "width":299,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某一课程页/u47.png"}},
{
              "id":"b95ad6371f584307b937c6844fb974c6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":598,
                  "y":150},
                "size":{
                  "width":300,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0bab915e39f94b989c48d87abc4effb3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":598,
                      "y":150},
                    "size":{
                      "width":300,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某一课程页/u51.png"}},
{
              "id":"25a7950abefe47ec89d1947921f9b35e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":180},
                "size":{
                  "width":299,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"874daabf465c439ba1682b3608bc8689",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":180},
                    "size":{
                      "width":299,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某一课程页/u47.png"}},
{
              "id":"31fdd46ad96242e8b610748c958c9728",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":299,
                  "y":180},
                "size":{
                  "width":299,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9f442b24e4614682976187ba94b572a3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":299,
                      "y":180},
                    "size":{
                      "width":299,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某一课程页/u47.png"}},
{
              "id":"59351d266ee44e308c41dc2ee6be91b7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":598,
                  "y":180},
                "size":{
                  "width":300,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fe98f960fd534e86b213f70e16a2e1ae",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":598,
                      "y":180},
                    "size":{
                      "width":300,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某一课程页/u51.png"}},
{
              "id":"3aef472bd876424bb883bf472c935773",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":300},
                "size":{
                  "width":299,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"49e6035b5d4545a5b81402876df1024f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":300},
                    "size":{
                      "width":299,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某一课程页/u47.png"}},
{
              "id":"5316a868e38149ea9a3713b8d4b5de1a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":299,
                  "y":300},
                "size":{
                  "width":299,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"33401b5978d54440955b57d706caae12",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":299,
                      "y":300},
                    "size":{
                      "width":299,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某一课程页/u47.png"}},
{
              "id":"3f2ad213bef34b6ab2f1b0b61c011142",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":598,
                  "y":300},
                "size":{
                  "width":300,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6a06ae400662446388ea5ddcc1a68310",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":598,
                      "y":300},
                    "size":{
                      "width":300,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某一课程页/u51.png"}},
{
              "id":"e1f8c4ba15224a21b25c0eaa7d427e30",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":210},
                "size":{
                  "width":299,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"44c430364a33478c97909a94c47940f7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":210},
                    "size":{
                      "width":299,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某一课程页/u47.png"}},
{
              "id":"f47420c6ea954cc49977369bf5d9a481",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":299,
                  "y":210},
                "size":{
                  "width":299,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6d46a0b15492474b8097dbf85202991f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":299,
                      "y":210},
                    "size":{
                      "width":299,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某一课程页/u47.png"}},
{
              "id":"57366286dd814fd58ed28af03362be87",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":598,
                  "y":210},
                "size":{
                  "width":300,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"adbc4982a9cc423a99319d53825174c5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":598,
                      "y":210},
                    "size":{
                      "width":300,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某一课程页/u51.png"}},
{
              "id":"0dff32c3563543138c7f4438843e4d3f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":240},
                "size":{
                  "width":299,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ec1d66867ddc4a658332f6987c40a6c8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":240},
                    "size":{
                      "width":299,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某一课程页/u47.png"}},
{
              "id":"caba0767df3f4d37875de3f052f14ec8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":299,
                  "y":240},
                "size":{
                  "width":299,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2aaf93680ec049a6b4bbb530bdc05ffd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":299,
                      "y":240},
                    "size":{
                      "width":299,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某一课程页/u47.png"}},
{
              "id":"488d796f99204523905623646664af53",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":598,
                  "y":240},
                "size":{
                  "width":300,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"00faa60ccb194dd5b21c01790b5c4404",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":598,
                      "y":240},
                    "size":{
                      "width":300,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某一课程页/u51.png"}},
{
              "id":"a2a039f340ef4a03a4501aeae2afab95",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":270},
                "size":{
                  "width":299,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fb5ad157f8ab476796fc1c5391e5d8db",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":270},
                    "size":{
                      "width":299,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某一课程页/u47.png"}},
{
              "id":"e343ea49ef2245749573e25b1c6f66e0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":299,
                  "y":270},
                "size":{
                  "width":299,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fcd00f78245644a4b15934531596ff6a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":299,
                      "y":270},
                    "size":{
                      "width":299,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某一课程页/u47.png"}},
{
              "id":"2b7d7dfe6e284d3c94a24f9f1d59774d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":598,
                  "y":270},
                "size":{
                  "width":300,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a5d66460510944829c5a09dca39cb312",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":598,
                      "y":270},
                    "size":{
                      "width":300,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某一课程页/u51.png"}}]},
{
          "id":"535c04bf4db54d5f9c9edeee999a66c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":260,
              "y":190},
            "size":{
              "width":370,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"263a3743048a4c1cac0a38606caeffcf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":260,
                  "y":190},
                "size":{
                  "width":370,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "5bc0bc7e763047a1b4d9287d5a31fe5e":{
      "scriptId":"u0"},
    "25f1e73eb8cd40f3afcfdee6cfda75d8":{
      "scriptId":"u1"},
    "38fc6c7315124635ab5202f5d2d4807b":{
      "scriptId":"u2"},
    "a7404297938b4964ac349b772f2dd45d":{
      "scriptId":"u3"},
    "9ab3882eb150499ba9a3482caa7ba0ce":{
      "scriptId":"u4"},
    "b329ddef22554ac08aa8e34a843fd3f7":{
      "scriptId":"u5"},
    "802c576f5e4a4e698ec0a07e2e48523e":{
      "scriptId":"u6"},
    "1c47d198588640248a798ce961c08244":{
      "scriptId":"u7"},
    "907a58fb91b94e65bf925dc4f9e190ee":{
      "scriptId":"u8"},
    "c116158ecc1a4df6b6d69eb1ce3abc36":{
      "scriptId":"u9"},
    "14271d4d10e44024acfb7bc60518c238":{
      "scriptId":"u10"},
    "72abbb1b1f604ee8b2c3e276de2b731d":{
      "scriptId":"u11"},
    "bc0e372fff7548f594bc0877694fd156":{
      "scriptId":"u12"},
    "52135b265a884575ae507ba0662bc1e7":{
      "scriptId":"u13"},
    "098730e012bc4e3787b7ef68a4b7b512":{
      "scriptId":"u14"},
    "0a45979220494000963df10c494e73da":{
      "scriptId":"u15"},
    "9194cb3781b5422b87df7386afe0de79":{
      "scriptId":"u16"},
    "e0c709214a734e52ac93eac6ff2074bf":{
      "scriptId":"u17"},
    "398bcfd24c4447d5b688e668a8e5d1ff":{
      "scriptId":"u18"},
    "fdda9f806b774ef99cf0a63323b1aa9f":{
      "scriptId":"u19"},
    "2928db9f032249749b558926e805ce69":{
      "scriptId":"u20"},
    "e1b928471cb74ba38b3fda24783f11fe":{
      "scriptId":"u21"},
    "a774a77880c443749cda7626ef230227":{
      "scriptId":"u22"},
    "44e832ed0f5b4d3fb3798c4bc6fe6681":{
      "scriptId":"u23"},
    "00796e32090c4c66854f675ab8041ce5":{
      "scriptId":"u24"},
    "bf16a4b1aad642c4b964832654edcdce":{
      "scriptId":"u25"},
    "ab8f6640b11e42708b3eae01ae0deca7":{
      "scriptId":"u26"},
    "1cb71bb5c5d54d9994f1f42aea869f51":{
      "scriptId":"u27"},
    "1d64add7969d471a8d7a5d0c2b466f99":{
      "scriptId":"u28"},
    "5fcd7081edd0452585f411c02f349153":{
      "scriptId":"u29"},
    "ce27abb791c34312b9ca1b1f6895c0d1":{
      "scriptId":"u30"},
    "e1b7cac832b84189a1ea47b941f63a28":{
      "scriptId":"u31"},
    "40af750d171b495392915519647741e3":{
      "scriptId":"u32"},
    "06f370825f394d208cc93c5e57b99fe3":{
      "scriptId":"u33"},
    "05c6267ff3814ce6827b0297d3a1ac60":{
      "scriptId":"u34"},
    "8fa94ce70b0d4cac84f560beb16755c2":{
      "scriptId":"u35"},
    "d627e9645b0f43759031897ae3f83d4d":{
      "scriptId":"u36"},
    "8617a5f5c0e64190b796c354d19c7a6a":{
      "scriptId":"u37"},
    "9f04f101ce82472a9487099ac43e0a60":{
      "scriptId":"u38"},
    "cbe9725e1cbc487b8bbefe39480f52df":{
      "scriptId":"u39"},
    "d67fd0664cb94f009709f22152c289eb":{
      "scriptId":"u40"},
    "57bcc3c2277a4aa59f1cb94e7a471b6f":{
      "scriptId":"u41"},
    "7e379b95fad44f69b40d94cadccd69f0":{
      "scriptId":"u42"},
    "dad536c5f08f43f29c9eaed5a4348d02":{
      "scriptId":"u43"},
    "a9b02659625441cb9d200e7ba3a0ebb6":{
      "scriptId":"u44"},
    "2e0a5e6ea1b74416aea0c395b60425b6":{
      "scriptId":"u45"},
    "f349d188d65346229c96f4da9c978e01":{
      "scriptId":"u46"},
    "a60c80525591451cbdeaba138f282d2e":{
      "scriptId":"u47"},
    "0dbf9bb501624cbfa2b7f437d795dbd2":{
      "scriptId":"u48"},
    "071ab031cb444fcb945a4b7c2bc41cee":{
      "scriptId":"u49"},
    "9bbda4428d944d278ea33d2677a46505":{
      "scriptId":"u50"},
    "d1b70b4fc3eb4fa7ae78c9e19009f24a":{
      "scriptId":"u51"},
    "cead48be7d464037bf104566cf2e5825":{
      "scriptId":"u52"},
    "aa36416ee17642998a1f4c2ae5c0f9f4":{
      "scriptId":"u53"},
    "603a2c02536048c78273a249183dd59d":{
      "scriptId":"u54"},
    "865824b5921649b0b06dd999fc882cb2":{
      "scriptId":"u55"},
    "846e95087d014b85a361fddaee2e711d":{
      "scriptId":"u56"},
    "a6144fb3f8ab4f52ad66d305feed9e12":{
      "scriptId":"u57"},
    "dc696d76b5c7467382b9c8dfe45a55e0":{
      "scriptId":"u58"},
    "2f392f5e7cc741dbb0bef9ac9f02aafa":{
      "scriptId":"u59"},
    "3f686081ed024bffb77c5a3d6c434505":{
      "scriptId":"u60"},
    "bba3868152b84c3ea36a664bc436ba65":{
      "scriptId":"u61"},
    "acd130535efe48218ea2090d65fd4977":{
      "scriptId":"u62"},
    "88a0e7f7e1d74896b4b61d61ac8b11d2":{
      "scriptId":"u63"},
    "b3b719e07c844ef881450b8b43f58d8c":{
      "scriptId":"u64"},
    "b5e5e8241ba04dc691f2158c4b2f5b17":{
      "scriptId":"u65"},
    "b04a3a6807e04d05b8c38056bca2fe2a":{
      "scriptId":"u66"},
    "491db4242652492ab4673873c044e469":{
      "scriptId":"u67"},
    "968308bdce454a97892e5fdc53615290":{
      "scriptId":"u68"},
    "23840b16e3a947188c6167233b99a8de":{
      "scriptId":"u69"},
    "83f024f8146c4019ad25378176c46f6e":{
      "scriptId":"u70"},
    "89dc29c161324de9ad1d9caf398f1610":{
      "scriptId":"u71"},
    "8b7a4b69301f4e22b60e6dfcebc48d64":{
      "scriptId":"u72"},
    "917c40f20ed340879ad48d80cdc02580":{
      "scriptId":"u73"},
    "85f39b8b136745b19badb1b31a394f28":{
      "scriptId":"u74"},
    "3c5c3c6a011f4a198bb1b8532d402c87":{
      "scriptId":"u75"},
    "6def6653c2ba4c03a779150880272239":{
      "scriptId":"u76"},
    "6456406a43264ca9b96204a7ae79d126":{
      "scriptId":"u77"},
    "a2ead798cf304c48bb92c32f0d16c66b":{
      "scriptId":"u78"},
    "80386216ccb046baa0cf1d7fc17913b7":{
      "scriptId":"u79"},
    "12d133b903884bb5923ac065d3089af4":{
      "scriptId":"u80"},
    "b95ad6371f584307b937c6844fb974c6":{
      "scriptId":"u81"},
    "0bab915e39f94b989c48d87abc4effb3":{
      "scriptId":"u82"},
    "25a7950abefe47ec89d1947921f9b35e":{
      "scriptId":"u83"},
    "874daabf465c439ba1682b3608bc8689":{
      "scriptId":"u84"},
    "31fdd46ad96242e8b610748c958c9728":{
      "scriptId":"u85"},
    "9f442b24e4614682976187ba94b572a3":{
      "scriptId":"u86"},
    "59351d266ee44e308c41dc2ee6be91b7":{
      "scriptId":"u87"},
    "fe98f960fd534e86b213f70e16a2e1ae":{
      "scriptId":"u88"},
    "e1f8c4ba15224a21b25c0eaa7d427e30":{
      "scriptId":"u89"},
    "44c430364a33478c97909a94c47940f7":{
      "scriptId":"u90"},
    "f47420c6ea954cc49977369bf5d9a481":{
      "scriptId":"u91"},
    "6d46a0b15492474b8097dbf85202991f":{
      "scriptId":"u92"},
    "57366286dd814fd58ed28af03362be87":{
      "scriptId":"u93"},
    "adbc4982a9cc423a99319d53825174c5":{
      "scriptId":"u94"},
    "0dff32c3563543138c7f4438843e4d3f":{
      "scriptId":"u95"},
    "ec1d66867ddc4a658332f6987c40a6c8":{
      "scriptId":"u96"},
    "caba0767df3f4d37875de3f052f14ec8":{
      "scriptId":"u97"},
    "2aaf93680ec049a6b4bbb530bdc05ffd":{
      "scriptId":"u98"},
    "488d796f99204523905623646664af53":{
      "scriptId":"u99"},
    "00faa60ccb194dd5b21c01790b5c4404":{
      "scriptId":"u100"},
    "a2a039f340ef4a03a4501aeae2afab95":{
      "scriptId":"u101"},
    "fb5ad157f8ab476796fc1c5391e5d8db":{
      "scriptId":"u102"},
    "e343ea49ef2245749573e25b1c6f66e0":{
      "scriptId":"u103"},
    "fcd00f78245644a4b15934531596ff6a":{
      "scriptId":"u104"},
    "2b7d7dfe6e284d3c94a24f9f1d59774d":{
      "scriptId":"u105"},
    "a5d66460510944829c5a09dca39cb312":{
      "scriptId":"u106"},
    "3aef472bd876424bb883bf472c935773":{
      "scriptId":"u107"},
    "49e6035b5d4545a5b81402876df1024f":{
      "scriptId":"u108"},
    "5316a868e38149ea9a3713b8d4b5de1a":{
      "scriptId":"u109"},
    "33401b5978d54440955b57d706caae12":{
      "scriptId":"u110"},
    "3f2ad213bef34b6ab2f1b0b61c011142":{
      "scriptId":"u111"},
    "6a06ae400662446388ea5ddcc1a68310":{
      "scriptId":"u112"},
    "699e7a22e60048198a5ca2420b4dd15f":{
      "scriptId":"u113"},
    "6150ddb63dfa4e65a3bc73923c34263f":{
      "scriptId":"u114"},
    "7239a769df734d93a6cd3a112ba9b0db":{
      "scriptId":"u115"},
    "b3ccb723c21144078f68a6b4370227e1":{
      "scriptId":"u116"},
    "9d9a102e42b54b90bbec225445e7ca16":{
      "scriptId":"u117"},
    "2f29073beee54726a89e5c444b442dc3":{
      "scriptId":"u118"},
    "535c04bf4db54d5f9c9edeee999a66c5":{
      "scriptId":"u119"},
    "263a3743048a4c1cac0a38606caeffcf":{
      "scriptId":"u120"}}});