$axure.loadCurrentPage({
  "url":"某次测试页.html",
  "generationDate":new Date(1491295963460.59),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"78ee8df538d9448aa13748f5ca83d3a9",
    "type":"Axure:Page",
    "name":"某次测试页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"far",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8a439cf65ae545e58914b1fddd7ced8c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "size":{
              "width":1200,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6319981eea9c4521883c4912b954cfc8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "size":{
                  "width":1200,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u0.png"}},
{
          "id":"aea5a7d669054877b8d42a4949f40cf1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":27,
              "y":0},
            "size":{
              "width":202,
              "height":118}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a9e76745da44e29ad0610352f46fcfc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":27,
                  "y":0},
                "size":{
                  "width":202,
                  "height":118}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登陆后",
                      "target":{
                        "targetType":"page",
                        "url":"登陆后.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a1540f5f72fa4f1aaeb020f77625ad6f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1051,
              "y":20},
            "size":{
              "width":80,
              "height":80},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"100"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"126b929cc6644a249a8322f73226fe14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1051,
                  "y":20},
                "size":{
                  "width":80,
                  "height":80},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"100"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u4.png"}},
{
          "id":"b8d28a7566b749ba8859031146585b06",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":1134,
              "y":55},
            "size":{
              "width":24,
              "height":18},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"807493ee3f244cccb6ff41c0ae6ec4d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":1134,
                  "y":55},
                "size":{
                  "width":24,
                  "height":18},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"切换 set",
                      "objectsToFades":[{
                          "objectPath":["79edcbc5299b4988a869343eaf835215"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登陆后/u50.png"}},
{
          "id":"79edcbc5299b4988a869343eaf835215",
          "label":"set",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":false,
          "style":{
            "location":{
              "x":1127,
              "y":87},
            "size":{
              "width":40,
              "height":61},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9c874c0a2a24657bdb8532938f69bdc",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":40,
                  "height":61}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e27ce9fb927d46659a4a046f91ae6b3f",
                  "label":"设置与退出",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":40,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"640ede85be764efaba04ca7aadea0811",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":40,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/登陆后/设置与退出_u54.png"}},
{
                  "id":"4fc0699367c74e39906663df05faf7be",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":40,
                      "height":31}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ca67175fefc94e4c9e98135d4823bac9",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":30},
                        "size":{
                          "width":40,
                          "height":31}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/登陆后/u56.png"}}]}]},
{
          "id":"5d9431f4b6e34d439cbf0d9960086001",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":0,
              "y":130},
            "size":{
              "width":230,
              "height":803}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd6c86c094b3414db6f198e5bea79cd1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":0,
                  "y":130},
                "size":{
                  "width":230,
                  "height":803}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/某次测试页/u14.png"}},
{
          "id":"844b9b5e0282471ca2b6bc53dfe8db8d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":213},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"299564abae904c79b7527fc305c6a965",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":213},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登陆后",
                      "target":{
                        "targetType":"page",
                        "url":"登陆后.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5ce5028035c443f2ba2377360db2f694",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":308},
            "size":{
              "width":97,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e87fc917a1cf4583be82a1acef22220f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":308},
                "size":{
                  "width":97,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 公告栏主页面",
                      "target":{
                        "targetType":"page",
                        "url":"公告栏主页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ed485ededa074f06bff0c2fb6d0fbc89",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":400},
            "size":{
              "width":97,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c90a95717966428bbb017ce2ad46f756",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":400},
                "size":{
                  "width":97,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 讨论区主页面",
                      "target":{
                        "targetType":"page",
                        "url":"讨论区主页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7d3ba3755e2a43a9b710f69da7253fd4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":490},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"888f72f507e74edf80de4ab9fb9e0f77",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":490},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 成绩管理主页面",
                      "target":{
                        "targetType":"page",
                        "url":"成绩管理主页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1e6332c05cae47f8bc1a6ac96afda2c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF363636},
            "location":{
              "x":0,
              "y":933},
            "size":{
              "width":1200,
              "height":180}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a8daa1b1395414c8c1688b8376c84bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF363636},
                "location":{
                  "x":0,
                  "y":933},
                "size":{
                  "width":1200,
                  "height":180}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u18.png"}},
{
          "id":"a7d4ea6ef42341d199172f3d10842a63",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":59,
              "y":958},
            "size":{
              "width":87,
              "height":85}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"444d9b091b694c65b1e37e8d66a52b6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":59,
                  "y":958},
                "size":{
                  "width":87,
                  "height":85}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u20.jpg"}},
{
          "id":"1a582bf1a491455eab56708a1a0e8bd1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'方正舒体 Regular', '方正舒体'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":45,
              "y":1053},
            "size":{
              "width":126,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e71c85dac334827801ad529eb5942b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'方正舒体 Regular', '方正舒体'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":45,
                  "y":1053},
                "size":{
                  "width":126,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"652e8f53f8514e14b590043e65792454",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":600,
              "y":958},
            "size":{
              "width":117,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c90826b110c429f80a10c0f1ccfd60e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":600,
                  "y":958},
                "size":{
                  "width":117,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"033c0c9b2867496e86f609c6e858aa24",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":600,
              "y":1015},
            "size":{
              "width":77,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd18d7cc7a004d49aaf2e844f2711741",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":600,
                  "y":1015},
                "size":{
                  "width":77,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7aafa0acc778403481d7992198d850ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":693,
              "y":1015},
            "size":{
              "width":77,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a5b060a977745faa0f702d5de510da8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":693,
                  "y":1015},
                "size":{
                  "width":77,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6d4338189d7844f680a3133fd5559506",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":600,
              "y":1054},
            "size":{
              "width":77,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1689e428dd854294b1cb2251bccc9542",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":600,
                  "y":1054},
                "size":{
                  "width":77,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7279c14388e3433ab6eab9f3d20c2870",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":691,
              "y":1054},
            "size":{
              "width":77,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd17c4ed9ba44ae9940ff92b48bb971b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":691,
                  "y":1054},
                "size":{
                  "width":77,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bcd2db5730bf4b51ace51572aecf1575",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":920,
              "y":958},
            "size":{
              "width":117,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc70444667cd48989e628b0e7ebaa176",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":920,
                  "y":958},
                "size":{
                  "width":117,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"36f5bcaaf47a497595c01eba619b3d85",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":920,
              "y":1015},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"229150ab971e444e9c321e915c1b739b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":920,
                  "y":1015},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u36.png"}},
{
          "id":"b1e6301213384973b4d04d2c4fbf8b25",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1000,
              "y":1015},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"adad1836069b40da9ea4fe26d8b3fd97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1000,
                  "y":1015},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u36.png"}},
{
          "id":"540e76023e4141d2939147276be2bed7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":279,
              "y":192},
            "size":{
              "width":121,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3dfa508db1f44b8b54de7adca928043",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":279,
                  "y":192},
                "size":{
                  "width":121,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"21e84c4ab294441d805b4a5166cfafab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":279,
              "y":254},
            "size":{
              "width":852,
              "height":296}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de04465b50b34432ae36c04216645203",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":279,
                  "y":254},
                "size":{
                  "width":852,
                  "height":296}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"91515f16dbd84e479919cd9d7b6f4068",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":279,
              "y":620},
            "size":{
              "width":852,
              "height":270}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f2a25d78ea94342b4154a9745cec851",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":284,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1bcfd960f7ff4ab981f2707c4b7de855",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":284,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某次测试页/u51.png"}},
{
              "id":"01984622521f47d8a4d041e6715e7d9d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":284,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b4e4c7e252ca4beba8581d6d38c5a819",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":284,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某次测试页/u51.png"}},
{
              "id":"47ba480c2e5d4d5688ae5c3fec48741c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":284,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"44b8e657db0543f69c2f18126d951064",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":284,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某次测试页/u51.png"}},
{
              "id":"dfbc556c00b44eb7af02b91602cafb48",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":284,
                  "y":0},
                "size":{
                  "width":284,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"44dc0b95f192486e8ac2ac2812fe1d8c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":284,
                      "y":0},
                    "size":{
                      "width":284,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某次测试页/u51.png"}},
{
              "id":"f15edc7077f34191856778db9bfa61aa",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":284,
                  "y":30},
                "size":{
                  "width":284,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"768981d062844281b893e8c3dfc17843",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":284,
                      "y":30},
                    "size":{
                      "width":284,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某次测试页/u51.png"}},
{
              "id":"35d8fded43774edb9eaa63381e01d125",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":284,
                  "y":60},
                "size":{
                  "width":284,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"20445f30311343f9b55a90cc24ca7099",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":284,
                      "y":60},
                    "size":{
                      "width":284,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某次测试页/u51.png"}},
{
              "id":"752c951b77e348308b444bb8011d4481",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":568,
                  "y":0},
                "size":{
                  "width":284,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"19812a51eb6e48529d0976f7abd36fd2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":568,
                      "y":0},
                    "size":{
                      "width":284,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某次测试页/u55.png"}},
{
              "id":"4cd079804a61414ea8e23f446e052114",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":568,
                  "y":30},
                "size":{
                  "width":284,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bd1cc6599bc24250b05ea7a45aad1268",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":568,
                      "y":30},
                    "size":{
                      "width":284,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某次测试页/u55.png"}},
{
              "id":"7c048739c86f421187cb27913dfbc4da",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":568,
                  "y":60},
                "size":{
                  "width":284,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8eb515b5c33d44c19f67c0c375d597d3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":568,
                      "y":60},
                    "size":{
                      "width":284,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某次测试页/u55.png"}},
{
              "id":"5c4e3dc54a00497bbe4506c56b85c501",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":90},
                "size":{
                  "width":284,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6b206b7c14cb43c6aec1093da946d7f6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":90},
                    "size":{
                      "width":284,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某次测试页/u51.png"}},
{
              "id":"8f9fae6b7eff4308bff176b275f46551",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":284,
                  "y":90},
                "size":{
                  "width":284,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"83a6e71e8d234b74b2805311ccdcfd4d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":284,
                      "y":90},
                    "size":{
                      "width":284,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某次测试页/u51.png"}},
{
              "id":"1f4191a83b5843c29243d797f78d75f6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":568,
                  "y":90},
                "size":{
                  "width":284,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"42222304dee347df9bb5a7d3b3ede54d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":568,
                      "y":90},
                    "size":{
                      "width":284,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某次测试页/u55.png"}},
{
              "id":"3df4414f4f9f4374a1c70c07cdb7ef53",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":120},
                "size":{
                  "width":284,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2a76e3b2387b40cb960f4e311636dd5b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":120},
                    "size":{
                      "width":284,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某次测试页/u51.png"}},
{
              "id":"93b378d0cf894a3fb090b4171fae97f6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":284,
                  "y":120},
                "size":{
                  "width":284,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e9dbecbbecd949818ba8473a3f469dcf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":284,
                      "y":120},
                    "size":{
                      "width":284,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某次测试页/u51.png"}},
{
              "id":"8840b26c3eba43f79aa1fd8448f4946f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":568,
                  "y":120},
                "size":{
                  "width":284,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d8ef60851b1e44e3bb8012f27efc55a2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":568,
                      "y":120},
                    "size":{
                      "width":284,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某次测试页/u55.png"}},
{
              "id":"218e04a4efd846e1a397c9cad1ddefa7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":150},
                "size":{
                  "width":284,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d3d76293d9804fc58c95d417194c6771",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":150},
                    "size":{
                      "width":284,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某次测试页/u51.png"}},
{
              "id":"cc1facd005b049fa83215dacc4de508a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":284,
                  "y":150},
                "size":{
                  "width":284,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8ca5e193ba01444aa894af60c4ee3afb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":284,
                      "y":150},
                    "size":{
                      "width":284,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某次测试页/u51.png"}},
{
              "id":"c497944d4ffb48b69f6c7e998ad5773b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":568,
                  "y":150},
                "size":{
                  "width":284,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"05253f2c6995424d8a9f03b3c051390b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":568,
                      "y":150},
                    "size":{
                      "width":284,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某次测试页/u55.png"}},
{
              "id":"a45b76302efc45ad8d7bf4da261ab2f0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":180},
                "size":{
                  "width":284,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"98977673f3f24617b9dcafdb59c8c218",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":180},
                    "size":{
                      "width":284,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某次测试页/u51.png"}},
{
              "id":"de734e60c97f4712af15f4c6c795c6ed",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":284,
                  "y":180},
                "size":{
                  "width":284,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"799b4bf6da2242a7b3a5e06c35fb4365",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":284,
                      "y":180},
                    "size":{
                      "width":284,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某次测试页/u51.png"}},
{
              "id":"cf26d139c4bc4bea85059ad79108463a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":568,
                  "y":180},
                "size":{
                  "width":284,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"019140ed6de8480994cd71df70d2bd68",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":568,
                      "y":180},
                    "size":{
                      "width":284,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某次测试页/u55.png"}},
{
              "id":"8f71cbab2ea54dbc9ec4eb8638527a97",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":210},
                "size":{
                  "width":284,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"25750c2e36ee45a298f5dafbb83bde13",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":210},
                    "size":{
                      "width":284,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某次测试页/u51.png"}},
{
              "id":"c0806ce33d6d4b158b77b69124c31e3f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":284,
                  "y":210},
                "size":{
                  "width":284,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"918c8c237c414dc4bbe2c4ecc5ae44e5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":284,
                      "y":210},
                    "size":{
                      "width":284,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某次测试页/u51.png"}},
{
              "id":"84018f2460154eaea7355532869d0353",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":568,
                  "y":210},
                "size":{
                  "width":284,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"123e5b2393b5474c893f3e62935086a3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":568,
                      "y":210},
                    "size":{
                      "width":284,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某次测试页/u55.png"}},
{
              "id":"7616df1a98464d11bf5d860e2dd26a8d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":240},
                "size":{
                  "width":284,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f2543785dd494b7e9ea63ad854002dc3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":240},
                    "size":{
                      "width":284,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某次测试页/u99.png"}},
{
              "id":"d093085c1ef94050932892e0e165e9fa",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":284,
                  "y":240},
                "size":{
                  "width":284,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b1c6c30f382c48f9a42141f3f48dcf85",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":284,
                      "y":240},
                    "size":{
                      "width":284,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某次测试页/u99.png"}},
{
              "id":"e861c196827041eaae4df1296f9dfcc0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":568,
                  "y":240},
                "size":{
                  "width":284,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"56283db64e4b4d689f9798f7aeb5518a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":568,
                      "y":240},
                    "size":{
                      "width":284,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/某次测试页/u103.png"}}]},
{
          "id":"f54a5efa19eb41d0807086e6c238ee25",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":279,
              "y":582},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89e827bb39bc4d1db37e055088e406d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":279,
                  "y":582},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "8a439cf65ae545e58914b1fddd7ced8c":{
      "scriptId":"u0"},
    "6319981eea9c4521883c4912b954cfc8":{
      "scriptId":"u1"},
    "aea5a7d669054877b8d42a4949f40cf1":{
      "scriptId":"u2"},
    "4a9e76745da44e29ad0610352f46fcfc":{
      "scriptId":"u3"},
    "a1540f5f72fa4f1aaeb020f77625ad6f":{
      "scriptId":"u4"},
    "126b929cc6644a249a8322f73226fe14":{
      "scriptId":"u5"},
    "b8d28a7566b749ba8859031146585b06":{
      "scriptId":"u6"},
    "807493ee3f244cccb6ff41c0ae6ec4d2":{
      "scriptId":"u7"},
    "79edcbc5299b4988a869343eaf835215":{
      "scriptId":"u8"},
    "a9c874c0a2a24657bdb8532938f69bdc":{
      "scriptId":"u9"},
    "e27ce9fb927d46659a4a046f91ae6b3f":{
      "scriptId":"u10"},
    "640ede85be764efaba04ca7aadea0811":{
      "scriptId":"u11"},
    "4fc0699367c74e39906663df05faf7be":{
      "scriptId":"u12"},
    "ca67175fefc94e4c9e98135d4823bac9":{
      "scriptId":"u13"},
    "5d9431f4b6e34d439cbf0d9960086001":{
      "scriptId":"u14"},
    "bd6c86c094b3414db6f198e5bea79cd1":{
      "scriptId":"u15"},
    "844b9b5e0282471ca2b6bc53dfe8db8d":{
      "scriptId":"u16"},
    "299564abae904c79b7527fc305c6a965":{
      "scriptId":"u17"},
    "5ce5028035c443f2ba2377360db2f694":{
      "scriptId":"u18"},
    "e87fc917a1cf4583be82a1acef22220f":{
      "scriptId":"u19"},
    "ed485ededa074f06bff0c2fb6d0fbc89":{
      "scriptId":"u20"},
    "c90a95717966428bbb017ce2ad46f756":{
      "scriptId":"u21"},
    "7d3ba3755e2a43a9b710f69da7253fd4":{
      "scriptId":"u22"},
    "888f72f507e74edf80de4ab9fb9e0f77":{
      "scriptId":"u23"},
    "1e6332c05cae47f8bc1a6ac96afda2c6":{
      "scriptId":"u24"},
    "7a8daa1b1395414c8c1688b8376c84bf":{
      "scriptId":"u25"},
    "a7d4ea6ef42341d199172f3d10842a63":{
      "scriptId":"u26"},
    "444d9b091b694c65b1e37e8d66a52b6e":{
      "scriptId":"u27"},
    "1a582bf1a491455eab56708a1a0e8bd1":{
      "scriptId":"u28"},
    "0e71c85dac334827801ad529eb5942b8":{
      "scriptId":"u29"},
    "652e8f53f8514e14b590043e65792454":{
      "scriptId":"u30"},
    "6c90826b110c429f80a10c0f1ccfd60e":{
      "scriptId":"u31"},
    "033c0c9b2867496e86f609c6e858aa24":{
      "scriptId":"u32"},
    "fd18d7cc7a004d49aaf2e844f2711741":{
      "scriptId":"u33"},
    "7aafa0acc778403481d7992198d850ec":{
      "scriptId":"u34"},
    "9a5b060a977745faa0f702d5de510da8":{
      "scriptId":"u35"},
    "6d4338189d7844f680a3133fd5559506":{
      "scriptId":"u36"},
    "1689e428dd854294b1cb2251bccc9542":{
      "scriptId":"u37"},
    "7279c14388e3433ab6eab9f3d20c2870":{
      "scriptId":"u38"},
    "dd17c4ed9ba44ae9940ff92b48bb971b":{
      "scriptId":"u39"},
    "bcd2db5730bf4b51ace51572aecf1575":{
      "scriptId":"u40"},
    "bc70444667cd48989e628b0e7ebaa176":{
      "scriptId":"u41"},
    "36f5bcaaf47a497595c01eba619b3d85":{
      "scriptId":"u42"},
    "229150ab971e444e9c321e915c1b739b":{
      "scriptId":"u43"},
    "b1e6301213384973b4d04d2c4fbf8b25":{
      "scriptId":"u44"},
    "adad1836069b40da9ea4fe26d8b3fd97":{
      "scriptId":"u45"},
    "540e76023e4141d2939147276be2bed7":{
      "scriptId":"u46"},
    "c3dfa508db1f44b8b54de7adca928043":{
      "scriptId":"u47"},
    "21e84c4ab294441d805b4a5166cfafab":{
      "scriptId":"u48"},
    "de04465b50b34432ae36c04216645203":{
      "scriptId":"u49"},
    "91515f16dbd84e479919cd9d7b6f4068":{
      "scriptId":"u50"},
    "7f2a25d78ea94342b4154a9745cec851":{
      "scriptId":"u51"},
    "1bcfd960f7ff4ab981f2707c4b7de855":{
      "scriptId":"u52"},
    "dfbc556c00b44eb7af02b91602cafb48":{
      "scriptId":"u53"},
    "44dc0b95f192486e8ac2ac2812fe1d8c":{
      "scriptId":"u54"},
    "752c951b77e348308b444bb8011d4481":{
      "scriptId":"u55"},
    "19812a51eb6e48529d0976f7abd36fd2":{
      "scriptId":"u56"},
    "01984622521f47d8a4d041e6715e7d9d":{
      "scriptId":"u57"},
    "b4e4c7e252ca4beba8581d6d38c5a819":{
      "scriptId":"u58"},
    "f15edc7077f34191856778db9bfa61aa":{
      "scriptId":"u59"},
    "768981d062844281b893e8c3dfc17843":{
      "scriptId":"u60"},
    "4cd079804a61414ea8e23f446e052114":{
      "scriptId":"u61"},
    "bd1cc6599bc24250b05ea7a45aad1268":{
      "scriptId":"u62"},
    "47ba480c2e5d4d5688ae5c3fec48741c":{
      "scriptId":"u63"},
    "44b8e657db0543f69c2f18126d951064":{
      "scriptId":"u64"},
    "35d8fded43774edb9eaa63381e01d125":{
      "scriptId":"u65"},
    "20445f30311343f9b55a90cc24ca7099":{
      "scriptId":"u66"},
    "7c048739c86f421187cb27913dfbc4da":{
      "scriptId":"u67"},
    "8eb515b5c33d44c19f67c0c375d597d3":{
      "scriptId":"u68"},
    "5c4e3dc54a00497bbe4506c56b85c501":{
      "scriptId":"u69"},
    "6b206b7c14cb43c6aec1093da946d7f6":{
      "scriptId":"u70"},
    "8f9fae6b7eff4308bff176b275f46551":{
      "scriptId":"u71"},
    "83a6e71e8d234b74b2805311ccdcfd4d":{
      "scriptId":"u72"},
    "1f4191a83b5843c29243d797f78d75f6":{
      "scriptId":"u73"},
    "42222304dee347df9bb5a7d3b3ede54d":{
      "scriptId":"u74"},
    "3df4414f4f9f4374a1c70c07cdb7ef53":{
      "scriptId":"u75"},
    "2a76e3b2387b40cb960f4e311636dd5b":{
      "scriptId":"u76"},
    "93b378d0cf894a3fb090b4171fae97f6":{
      "scriptId":"u77"},
    "e9dbecbbecd949818ba8473a3f469dcf":{
      "scriptId":"u78"},
    "8840b26c3eba43f79aa1fd8448f4946f":{
      "scriptId":"u79"},
    "d8ef60851b1e44e3bb8012f27efc55a2":{
      "scriptId":"u80"},
    "218e04a4efd846e1a397c9cad1ddefa7":{
      "scriptId":"u81"},
    "d3d76293d9804fc58c95d417194c6771":{
      "scriptId":"u82"},
    "cc1facd005b049fa83215dacc4de508a":{
      "scriptId":"u83"},
    "8ca5e193ba01444aa894af60c4ee3afb":{
      "scriptId":"u84"},
    "c497944d4ffb48b69f6c7e998ad5773b":{
      "scriptId":"u85"},
    "05253f2c6995424d8a9f03b3c051390b":{
      "scriptId":"u86"},
    "a45b76302efc45ad8d7bf4da261ab2f0":{
      "scriptId":"u87"},
    "98977673f3f24617b9dcafdb59c8c218":{
      "scriptId":"u88"},
    "de734e60c97f4712af15f4c6c795c6ed":{
      "scriptId":"u89"},
    "799b4bf6da2242a7b3a5e06c35fb4365":{
      "scriptId":"u90"},
    "cf26d139c4bc4bea85059ad79108463a":{
      "scriptId":"u91"},
    "019140ed6de8480994cd71df70d2bd68":{
      "scriptId":"u92"},
    "8f71cbab2ea54dbc9ec4eb8638527a97":{
      "scriptId":"u93"},
    "25750c2e36ee45a298f5dafbb83bde13":{
      "scriptId":"u94"},
    "c0806ce33d6d4b158b77b69124c31e3f":{
      "scriptId":"u95"},
    "918c8c237c414dc4bbe2c4ecc5ae44e5":{
      "scriptId":"u96"},
    "84018f2460154eaea7355532869d0353":{
      "scriptId":"u97"},
    "123e5b2393b5474c893f3e62935086a3":{
      "scriptId":"u98"},
    "7616df1a98464d11bf5d860e2dd26a8d":{
      "scriptId":"u99"},
    "f2543785dd494b7e9ea63ad854002dc3":{
      "scriptId":"u100"},
    "d093085c1ef94050932892e0e165e9fa":{
      "scriptId":"u101"},
    "b1c6c30f382c48f9a42141f3f48dcf85":{
      "scriptId":"u102"},
    "e861c196827041eaae4df1296f9dfcc0":{
      "scriptId":"u103"},
    "56283db64e4b4d689f9798f7aeb5518a":{
      "scriptId":"u104"},
    "f54a5efa19eb41d0807086e6c238ee25":{
      "scriptId":"u105"},
    "89e827bb39bc4d1db37e055088e406d3":{
      "scriptId":"u106"}}});