$axure.loadCurrentPage({
  "url":"讨论区主页面.html",
  "generationDate":new Date(1491295964159.08),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"48ca938ae156427f876d5fdbee5ef0d4",
    "type":"Axure:Page",
    "name":"讨论区主页面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0180826f0599483eb86a726d8d1e8f70",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "size":{
              "width":1200,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afab2330494942c8b0b7a70681a6a13f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "size":{
                  "width":1200,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u0.png"}},
{
          "id":"2ab75b72855a4d598ebe273941b1fd44",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":27,
              "y":0},
            "size":{
              "width":202,
              "height":118}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a78db8c9dc44457a0acad102ad1876c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":27,
                  "y":0},
                "size":{
                  "width":202,
                  "height":118}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登陆后",
                      "target":{
                        "targetType":"page",
                        "url":"登陆后.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fc4bf093e5f345c7b122ade08b8abef2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1051,
              "y":20},
            "size":{
              "width":80,
              "height":80},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"100"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"699fd9cb335b4eca820ee5d264a409f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1051,
                  "y":20},
                "size":{
                  "width":80,
                  "height":80},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"100"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u4.png"}},
{
          "id":"5b4bab36a8564b398ba06b854f08110e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":0,
              "y":130},
            "size":{
              "width":230,
              "height":1330}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d182e8aa5f7b42caaea9f0512c4a3498",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":0,
                  "y":130},
                "size":{
                  "width":230,
                  "height":1330}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/讨论区主页面/u6.png"}},
{
          "id":"e038e56897da4a73a46f9760bd4162e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":213},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1cbe167533241f280cf2d37086656f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":213},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登陆后",
                      "target":{
                        "targetType":"page",
                        "url":"登陆后.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3372458ef8df4ee7aabf7d1a60517d4d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":308},
            "size":{
              "width":97,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3773b745a794810a255ff4948900c04",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":308},
                "size":{
                  "width":97,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 公告栏主页面",
                      "target":{
                        "targetType":"page",
                        "url":"公告栏主页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1b907ad207fa403b88cf9cfc4c3d4228",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":400},
            "size":{
              "width":97,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8141a0b1b4154c7182518e5856e733ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":400},
                "size":{
                  "width":97,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 讨论区主页面",
                      "target":{
                        "targetType":"page",
                        "url":"讨论区主页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"db8d8286accd48ad85ab5e3b56bf6344",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":490},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e4db0f023614bacb344679f4e06a1ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":490},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 成绩管理主页面",
                      "target":{
                        "targetType":"page",
                        "url":"成绩管理主页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fab4387e535f4cdc947eb4f55c923c49",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF363636},
            "location":{
              "x":0,
              "y":1460},
            "size":{
              "width":1200,
              "height":180}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"855c3d7494d54497a4aa7477eda70d2e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF363636},
                "location":{
                  "x":0,
                  "y":1460},
                "size":{
                  "width":1200,
                  "height":180}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u18.png"}},
{
          "id":"0bbb2cf8179b4b43aa584f6a45d5d773",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":59,
              "y":1485},
            "size":{
              "width":87,
              "height":85}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83fca18dd71b473081f4b05c24532b60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":59,
                  "y":1485},
                "size":{
                  "width":87,
                  "height":85}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u20.jpg"}},
{
          "id":"95bcc0facdb24c2682ddd765da464259",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'方正舒体 Regular', '方正舒体'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":45,
              "y":1580},
            "size":{
              "width":126,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"554204c62b5248e8ac5a1aaa530fc6cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'方正舒体 Regular', '方正舒体'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":45,
                  "y":1580},
                "size":{
                  "width":126,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3cb51a708cba406196f39d88d44a4b4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":707,
              "y":1485},
            "size":{
              "width":117,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1664232d141416fa829ca36e3ddd3f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":707,
                  "y":1485},
                "size":{
                  "width":117,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"21fc88e61ec94e5c9d3a7c5e0cd79bb6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":707,
              "y":1542},
            "size":{
              "width":77,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1dbe34585884dd2805064b8caf94848",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":707,
                  "y":1542},
                "size":{
                  "width":77,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"93abf1d0545f4e12be527161b62e45e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":800,
              "y":1542},
            "size":{
              "width":77,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3935aa8651c458983e9183578c1c771",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":800,
                  "y":1542},
                "size":{
                  "width":77,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"61b4b38071d440cd94a0219389489de5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":707,
              "y":1581},
            "size":{
              "width":77,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b719a9aee084f9a8c7841fbf21d4d2e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":707,
                  "y":1581},
                "size":{
                  "width":77,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0690793faef14f889c62017a79cdf630",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":798,
              "y":1581},
            "size":{
              "width":77,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8798056d2d441bf935a07ff1f644437",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":798,
                  "y":1581},
                "size":{
                  "width":77,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1d1508993ff44ef9958e26c7e0563653",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":1027,
              "y":1485},
            "size":{
              "width":117,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27213f13fede4d8bb62cf7b7fe2a7b93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":1027,
                  "y":1485},
                "size":{
                  "width":117,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bf9daea8b9fc476a926b8cd253d591a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1027,
              "y":1542},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52f330817f1145808fec07621821ab0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1027,
                  "y":1542},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u36.png"}},
{
          "id":"0b80ed5368db4a8bb2965403a11f77d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1107,
              "y":1542},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6eef7826154b4b3ab32f71c8ac29124f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1107,
                  "y":1542},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u36.png"}},
{
          "id":"f08c7a55e2bc4f98aa119819c510f93a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":1134,
              "y":55},
            "size":{
              "width":24,
              "height":18},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b96bedf143ff4e969d6825d5507fbe90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":1134,
                  "y":55},
                "size":{
                  "width":24,
                  "height":18},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"切换 set",
                      "objectsToFades":[{
                          "objectPath":["fb858aa8524a4fa28120931a8e04ad1b"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登陆后/u50.png"}},
{
          "id":"fb858aa8524a4fa28120931a8e04ad1b",
          "label":"set",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":false,
          "style":{
            "location":{
              "x":1127,
              "y":87},
            "size":{
              "width":40,
              "height":61},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a96175a05b94cf0970b25120050e8d1",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":40,
                  "height":61}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4ec4147ad62247a3bef12a31db636273",
                  "label":"设置与退出",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":40,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cada772f7df8492a93551950d696e702",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":40,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/登陆后/设置与退出_u54.png"}},
{
                  "id":"66b7f02437874c009e230b381ec56432",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":40,
                      "height":31}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"411bd06a4ccd45d58e12297ff1d722ca",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":30},
                        "size":{
                          "width":40,
                          "height":31}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/登陆后/u56.png"}}]}]},
{
          "id":"eb619c06cd10494c87f1a60f6f643340",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":1400},
            "size":{
              "width":640,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/公告栏主页面/u54_line.png"}},
{
          "id":"d60dc857965e4500889036a77e8d11ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":280,
              "y":1420},
            "size":{
              "width":100,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92dbca758d7b42b5aaa0d235fb5d36d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":280,
                  "y":1420},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/公告栏主页面/u55.png"}},
{
          "id":"0ffb998c78cb484390007f362f8c8d73",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":390,
              "y":1420},
            "size":{
              "width":30,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce6a811ec3844a3c8fe9cd516eb029ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":390,
                  "y":1420},
                "size":{
                  "width":30,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/公告栏主页面/u57.png"}},
{
          "id":"a9ae7a5d2efb4393a9568427745ff661",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":430,
              "y":1420},
            "size":{
              "width":30,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ca6a0084c244674a5273a6d79170423",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":430,
                  "y":1420},
                "size":{
                  "width":30,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/公告栏主页面/u57.png"}},
{
          "id":"7cc4d8ad35f44232af05be64f44f2aae",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":470,
              "y":1420},
            "size":{
              "width":30,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f43edd089eaa40479788fdf12893405c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":470,
                  "y":1420},
                "size":{
                  "width":30,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/公告栏主页面/u57.png"}},
{
          "id":"f85b25a2910b41d5864bb24717d002fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":510,
              "y":1420},
            "size":{
              "width":30,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"853fe48d38964257a61db1ebf263211f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":510,
                  "y":1420},
                "size":{
                  "width":30,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/公告栏主页面/u57.png"}},
{
          "id":"59731838dc694f6d8478de7d69a2fdd3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":550,
              "y":1420},
            "size":{
              "width":30,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a5927a4f90146baa607af1eee90ce60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":550,
                  "y":1420},
                "size":{
                  "width":30,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/公告栏主页面/u57.png"}},
{
          "id":"6832d47e4a1b49e8b7f19255facb3531",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":590,
              "y":1420},
            "size":{
              "width":30,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0db6b5d31b414905b6a1e72c98e3faac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":590,
                  "y":1420},
                "size":{
                  "width":30,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/公告栏主页面/u57.png"}},
{
          "id":"518162fa60364391b577f285677aedaf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":697,
              "y":1420},
            "size":{
              "width":30,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79dbf5c9b9e744beabc2628d22d9b327",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":697,
                  "y":1420},
                "size":{
                  "width":30,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/公告栏主页面/u57.png"}},
{
          "id":"9556e40500554bbf92102d717307b1c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":737,
              "y":1420},
            "size":{
              "width":30,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab6cf777a09a4edab9ff3e4e54a1e031",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":737,
                  "y":1420},
                "size":{
                  "width":30,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/公告栏主页面/u57.png"}},
{
          "id":"d7096e2b738e45fba6ea0ca4174c88b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":777,
              "y":1420},
            "size":{
              "width":30,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37548ca72362446c9ab5ed643c1879aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":777,
                  "y":1420},
                "size":{
                  "width":30,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/公告栏主页面/u57.png"}},
{
          "id":"2de65527898b447c99dbb1e10914df3c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":817,
              "y":1420},
            "size":{
              "width":100,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1974efa76be4d77bf3a763328a1a4b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":817,
                  "y":1420},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/公告栏主页面/u55.png"}},
{
          "id":"f1bf3432ef034d8caa89536c3a65f5f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":627,
              "y":1421},
            "size":{
              "width":64,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b53802280dd4a4b9831306dac5f162d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":627,
                  "y":1421},
                "size":{
                  "width":64,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"32d9c85551d94b7996807b364d347be9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":280,
              "y":180},
            "size":{
              "width":97,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc5c408084794494b4472d72c85cb9ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":280,
                  "y":180},
                "size":{
                  "width":97,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cb1a6bb096ce4bcbbc8465b930f3006f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF00CC66},
            "location":{
              "x":280,
              "y":261},
            "size":{
              "width":130,
              "height":49},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF00FF66},
            "cornerRadiusTopLeft":"5",
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45d1b69602484eaebaae4bf47998f3f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CC66},
                "location":{
                  "x":280,
                  "y":261},
                "size":{
                  "width":130,
                  "height":49},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF00FF66},
                "cornerRadiusTopLeft":"5",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 问题发布页",
                      "target":{
                        "targetType":"page",
                        "url":"问题发布页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/讨论区主页面/u73.png"}},
{
          "id":"35511be741c64e9dadfd5d66de5418fb",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":227},
            "size":{
              "width":900,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/讨论区主页面/u75_line.png"}},
{
          "id":"4bffa2b5a1b940f788d8bfc54395be99",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":788,
              "y":180},
            "size":{
              "width":303,
              "height":37}},
          "adaptiveStyles":{
},
          "placeholderText":"搜索主题/回复/评论等"},
{
          "id":"e02abd1703ba43eb92c6a5b0ebec18d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF00FF33,
              "opacity":1},
            "location":{
              "x":1105,
              "y":180},
            "size":{
              "width":85,
              "height":37},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF00FF66},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca0944540d66425d974a5a8cc428f231",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF00FF33,
                  "opacity":1},
                "location":{
                  "x":1105,
                  "y":180},
                "size":{
                  "width":85,
                  "height":37},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF00FF66},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/讨论区主页面/u77.png"}},
{
          "id":"3f869de9ce0d482680745e151192c2e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":350},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf75d75a23ec44bebae8348696025ec7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":350},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"35486142bc1940b88067cd945e3d94a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":681},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3313c271f170402ba483ff1d7659a78d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":681},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5fb31cc91c464af9b76fd69187012f6e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":455},
            "size":{
              "width":900,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/讨论区主页面/u75_line.png"}},
{
          "id":"fe080c5c7eba4f6d871932490e4841fa",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":538},
            "size":{
              "width":900,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/讨论区主页面/u75_line.png"}},
{
          "id":"27ac6aa860e24cf4bf1129f7b2dc6042",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":280,
              "y":421},
            "size":{
              "width":265,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2fe4ed94f784fd88da287e660d72048",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":280,
                  "y":421},
                "size":{
                  "width":265,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b26c4b9e5369444ba22f8431052bb034",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":280,
              "y":499},
            "size":{
              "width":265,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b3924aa0b9d45e684e79ec9aafa7b75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":280,
                  "y":499},
                "size":{
                  "width":265,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"210fc738480740ba81c616949d99d675",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":620},
            "size":{
              "width":900,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/讨论区主页面/u75_line.png"}},
{
          "id":"5d8b8c43b56443e48c88670d9c37f2d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":280,
              "y":582},
            "size":{
              "width":481,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb2a4a91fe09400a8f4056b77ee57665",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":280,
                  "y":582},
                "size":{
                  "width":481,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"49875987c2e64b619ce952abdb504dae",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":730},
            "size":{
              "width":910,
              "height":67}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0add0b03cf68411c9fbf3a0bde601a94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":730},
                "size":{
                  "width":910,
                  "height":67}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"80849ec0644f4f5782f9b36cdac2c041",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":807},
            "size":{
              "width":900,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/讨论区主页面/u75_line.png"}},
{
          "id":"08961dcd31b1460bacc094762fae15fc",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":378},
            "size":{
              "width":900,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/讨论区主页面/u75_line.png"}},
{
          "id":"ab86d9ba6a104e8e8921550522982e71",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":710},
            "size":{
              "width":900,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/讨论区主页面/u75_line.png"}},
{
          "id":"ac4ec5623f854ecdb1d765b1aa71b5f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":827},
            "size":{
              "width":910,
              "height":67}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8392a315054497782c7665ac44cae32",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":827},
                "size":{
                  "width":910,
                  "height":67}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0e649a151aac44e1811846780135ca1c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":904},
            "size":{
              "width":900,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/讨论区主页面/u75_line.png"}},
{
          "id":"0cf6b3a9977c43d5b6e40cc05fc5c028",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":924},
            "size":{
              "width":910,
              "height":67}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ef92b8a526749a4a30c15832a84955c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":924},
                "size":{
                  "width":910,
                  "height":67}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"17d70c255e48450c991aecc207e95871",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":1001},
            "size":{
              "width":900,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/讨论区主页面/u75_line.png"}},
{
          "id":"2eb00364a5b041b18435dfa9b3155a23",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":1021.00006103516},
            "size":{
              "width":910,
              "height":67}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"857c9e6049f54cd39e541db2da2263a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":1021.00006103516},
                "size":{
                  "width":910,
                  "height":67}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"80be295b212e4bdeaec1ab3e60e433ce",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":1098},
            "size":{
              "width":900,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/讨论区主页面/u75_line.png"}},
{
          "id":"4c631487cea34935ba3f1011f1cf41f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":1118},
            "size":{
              "width":910,
              "height":67}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60b00ca2aadc45d2ade132d83f9570b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":1118},
                "size":{
                  "width":910,
                  "height":67}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7a37a860ebf64fd69099e1ba39b96571",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":1195},
            "size":{
              "width":900,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/讨论区主页面/u75_line.png"}},
{
          "id":"8bb5c9b3afb74319882109803db3faad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":1215},
            "size":{
              "width":910,
              "height":67}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e9ad67db1ee4d8fa377317f78b10ce6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":1215},
                "size":{
                  "width":910,
                  "height":67}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d89dbe63c86645098268f6971a66e8c5",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":1292},
            "size":{
              "width":900,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/讨论区主页面/u75_line.png"}},
{
          "id":"938ae6a67e9542bdabb14b1b9031063e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":1312},
            "size":{
              "width":910,
              "height":67}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24007c1c69b8444e8598c8a4520000fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":1312},
                "size":{
                  "width":910,
                  "height":67}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9ac49ac555d040afa75a90b1ed8602e8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":1389},
            "size":{
              "width":900,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/讨论区主页面/u75_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "0180826f0599483eb86a726d8d1e8f70":{
      "scriptId":"u0"},
    "afab2330494942c8b0b7a70681a6a13f":{
      "scriptId":"u1"},
    "2ab75b72855a4d598ebe273941b1fd44":{
      "scriptId":"u2"},
    "7a78db8c9dc44457a0acad102ad1876c":{
      "scriptId":"u3"},
    "fc4bf093e5f345c7b122ade08b8abef2":{
      "scriptId":"u4"},
    "699fd9cb335b4eca820ee5d264a409f0":{
      "scriptId":"u5"},
    "5b4bab36a8564b398ba06b854f08110e":{
      "scriptId":"u6"},
    "d182e8aa5f7b42caaea9f0512c4a3498":{
      "scriptId":"u7"},
    "e038e56897da4a73a46f9760bd4162e2":{
      "scriptId":"u8"},
    "f1cbe167533241f280cf2d37086656f6":{
      "scriptId":"u9"},
    "3372458ef8df4ee7aabf7d1a60517d4d":{
      "scriptId":"u10"},
    "a3773b745a794810a255ff4948900c04":{
      "scriptId":"u11"},
    "1b907ad207fa403b88cf9cfc4c3d4228":{
      "scriptId":"u12"},
    "8141a0b1b4154c7182518e5856e733ce":{
      "scriptId":"u13"},
    "db8d8286accd48ad85ab5e3b56bf6344":{
      "scriptId":"u14"},
    "9e4db0f023614bacb344679f4e06a1ca":{
      "scriptId":"u15"},
    "fab4387e535f4cdc947eb4f55c923c49":{
      "scriptId":"u16"},
    "855c3d7494d54497a4aa7477eda70d2e":{
      "scriptId":"u17"},
    "0bbb2cf8179b4b43aa584f6a45d5d773":{
      "scriptId":"u18"},
    "83fca18dd71b473081f4b05c24532b60":{
      "scriptId":"u19"},
    "95bcc0facdb24c2682ddd765da464259":{
      "scriptId":"u20"},
    "554204c62b5248e8ac5a1aaa530fc6cf":{
      "scriptId":"u21"},
    "3cb51a708cba406196f39d88d44a4b4b":{
      "scriptId":"u22"},
    "c1664232d141416fa829ca36e3ddd3f0":{
      "scriptId":"u23"},
    "21fc88e61ec94e5c9d3a7c5e0cd79bb6":{
      "scriptId":"u24"},
    "e1dbe34585884dd2805064b8caf94848":{
      "scriptId":"u25"},
    "93abf1d0545f4e12be527161b62e45e9":{
      "scriptId":"u26"},
    "b3935aa8651c458983e9183578c1c771":{
      "scriptId":"u27"},
    "61b4b38071d440cd94a0219389489de5":{
      "scriptId":"u28"},
    "3b719a9aee084f9a8c7841fbf21d4d2e":{
      "scriptId":"u29"},
    "0690793faef14f889c62017a79cdf630":{
      "scriptId":"u30"},
    "a8798056d2d441bf935a07ff1f644437":{
      "scriptId":"u31"},
    "1d1508993ff44ef9958e26c7e0563653":{
      "scriptId":"u32"},
    "27213f13fede4d8bb62cf7b7fe2a7b93":{
      "scriptId":"u33"},
    "bf9daea8b9fc476a926b8cd253d591a0":{
      "scriptId":"u34"},
    "52f330817f1145808fec07621821ab0f":{
      "scriptId":"u35"},
    "0b80ed5368db4a8bb2965403a11f77d0":{
      "scriptId":"u36"},
    "6eef7826154b4b3ab32f71c8ac29124f":{
      "scriptId":"u37"},
    "f08c7a55e2bc4f98aa119819c510f93a":{
      "scriptId":"u38"},
    "b96bedf143ff4e969d6825d5507fbe90":{
      "scriptId":"u39"},
    "fb858aa8524a4fa28120931a8e04ad1b":{
      "scriptId":"u40"},
    "9a96175a05b94cf0970b25120050e8d1":{
      "scriptId":"u41"},
    "4ec4147ad62247a3bef12a31db636273":{
      "scriptId":"u42"},
    "cada772f7df8492a93551950d696e702":{
      "scriptId":"u43"},
    "66b7f02437874c009e230b381ec56432":{
      "scriptId":"u44"},
    "411bd06a4ccd45d58e12297ff1d722ca":{
      "scriptId":"u45"},
    "eb619c06cd10494c87f1a60f6f643340":{
      "scriptId":"u46"},
    "d60dc857965e4500889036a77e8d11ac":{
      "scriptId":"u47"},
    "92dbca758d7b42b5aaa0d235fb5d36d5":{
      "scriptId":"u48"},
    "0ffb998c78cb484390007f362f8c8d73":{
      "scriptId":"u49"},
    "ce6a811ec3844a3c8fe9cd516eb029ee":{
      "scriptId":"u50"},
    "a9ae7a5d2efb4393a9568427745ff661":{
      "scriptId":"u51"},
    "0ca6a0084c244674a5273a6d79170423":{
      "scriptId":"u52"},
    "7cc4d8ad35f44232af05be64f44f2aae":{
      "scriptId":"u53"},
    "f43edd089eaa40479788fdf12893405c":{
      "scriptId":"u54"},
    "f85b25a2910b41d5864bb24717d002fa":{
      "scriptId":"u55"},
    "853fe48d38964257a61db1ebf263211f":{
      "scriptId":"u56"},
    "59731838dc694f6d8478de7d69a2fdd3":{
      "scriptId":"u57"},
    "5a5927a4f90146baa607af1eee90ce60":{
      "scriptId":"u58"},
    "6832d47e4a1b49e8b7f19255facb3531":{
      "scriptId":"u59"},
    "0db6b5d31b414905b6a1e72c98e3faac":{
      "scriptId":"u60"},
    "518162fa60364391b577f285677aedaf":{
      "scriptId":"u61"},
    "79dbf5c9b9e744beabc2628d22d9b327":{
      "scriptId":"u62"},
    "9556e40500554bbf92102d717307b1c9":{
      "scriptId":"u63"},
    "ab6cf777a09a4edab9ff3e4e54a1e031":{
      "scriptId":"u64"},
    "d7096e2b738e45fba6ea0ca4174c88b5":{
      "scriptId":"u65"},
    "37548ca72362446c9ab5ed643c1879aa":{
      "scriptId":"u66"},
    "2de65527898b447c99dbb1e10914df3c":{
      "scriptId":"u67"},
    "b1974efa76be4d77bf3a763328a1a4b2":{
      "scriptId":"u68"},
    "f1bf3432ef034d8caa89536c3a65f5f1":{
      "scriptId":"u69"},
    "6b53802280dd4a4b9831306dac5f162d":{
      "scriptId":"u70"},
    "32d9c85551d94b7996807b364d347be9":{
      "scriptId":"u71"},
    "dc5c408084794494b4472d72c85cb9ad":{
      "scriptId":"u72"},
    "cb1a6bb096ce4bcbbc8465b930f3006f":{
      "scriptId":"u73"},
    "45d1b69602484eaebaae4bf47998f3f8":{
      "scriptId":"u74"},
    "35511be741c64e9dadfd5d66de5418fb":{
      "scriptId":"u75"},
    "4bffa2b5a1b940f788d8bfc54395be99":{
      "scriptId":"u76"},
    "e02abd1703ba43eb92c6a5b0ebec18d8":{
      "scriptId":"u77"},
    "ca0944540d66425d974a5a8cc428f231":{
      "scriptId":"u78"},
    "3f869de9ce0d482680745e151192c2e0":{
      "scriptId":"u79"},
    "bf75d75a23ec44bebae8348696025ec7":{
      "scriptId":"u80"},
    "35486142bc1940b88067cd945e3d94a9":{
      "scriptId":"u81"},
    "3313c271f170402ba483ff1d7659a78d":{
      "scriptId":"u82"},
    "5fb31cc91c464af9b76fd69187012f6e":{
      "scriptId":"u83"},
    "fe080c5c7eba4f6d871932490e4841fa":{
      "scriptId":"u84"},
    "27ac6aa860e24cf4bf1129f7b2dc6042":{
      "scriptId":"u85"},
    "a2fe4ed94f784fd88da287e660d72048":{
      "scriptId":"u86"},
    "b26c4b9e5369444ba22f8431052bb034":{
      "scriptId":"u87"},
    "9b3924aa0b9d45e684e79ec9aafa7b75":{
      "scriptId":"u88"},
    "210fc738480740ba81c616949d99d675":{
      "scriptId":"u89"},
    "5d8b8c43b56443e48c88670d9c37f2d9":{
      "scriptId":"u90"},
    "fb2a4a91fe09400a8f4056b77ee57665":{
      "scriptId":"u91"},
    "49875987c2e64b619ce952abdb504dae":{
      "scriptId":"u92"},
    "0add0b03cf68411c9fbf3a0bde601a94":{
      "scriptId":"u93"},
    "80849ec0644f4f5782f9b36cdac2c041":{
      "scriptId":"u94"},
    "08961dcd31b1460bacc094762fae15fc":{
      "scriptId":"u95"},
    "ab86d9ba6a104e8e8921550522982e71":{
      "scriptId":"u96"},
    "ac4ec5623f854ecdb1d765b1aa71b5f7":{
      "scriptId":"u97"},
    "e8392a315054497782c7665ac44cae32":{
      "scriptId":"u98"},
    "0e649a151aac44e1811846780135ca1c":{
      "scriptId":"u99"},
    "0cf6b3a9977c43d5b6e40cc05fc5c028":{
      "scriptId":"u100"},
    "4ef92b8a526749a4a30c15832a84955c":{
      "scriptId":"u101"},
    "17d70c255e48450c991aecc207e95871":{
      "scriptId":"u102"},
    "2eb00364a5b041b18435dfa9b3155a23":{
      "scriptId":"u103"},
    "857c9e6049f54cd39e541db2da2263a2":{
      "scriptId":"u104"},
    "80be295b212e4bdeaec1ab3e60e433ce":{
      "scriptId":"u105"},
    "4c631487cea34935ba3f1011f1cf41f1":{
      "scriptId":"u106"},
    "60b00ca2aadc45d2ade132d83f9570b0":{
      "scriptId":"u107"},
    "7a37a860ebf64fd69099e1ba39b96571":{
      "scriptId":"u108"},
    "8bb5c9b3afb74319882109803db3faad":{
      "scriptId":"u109"},
    "7e9ad67db1ee4d8fa377317f78b10ce6":{
      "scriptId":"u110"},
    "d89dbe63c86645098268f6971a66e8c5":{
      "scriptId":"u111"},
    "938ae6a67e9542bdabb14b1b9031063e":{
      "scriptId":"u112"},
    "24007c1c69b8444e8598c8a4520000fc":{
      "scriptId":"u113"},
    "9ac49ac555d040afa75a90b1ed8602e8":{
      "scriptId":"u114"}}});