$axure.loadCurrentPage({
  "url":"发布公告页.html",
  "generationDate":new Date(1491295963889.16),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"82d42bf4a64a4272a96fcb333c23004c",
    "type":"Axure:Page",
    "name":"发布公告页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8f83df5f3e784aca9ba8bb1b29190670",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "size":{
              "width":1200,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c19022b82d042f9a5043b07592c1b8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "size":{
                  "width":1200,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u0.png"}},
{
          "id":"f33f8d0750f3473b8fbc82be66814c15",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":27,
              "y":0},
            "size":{
              "width":202,
              "height":118}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce5ea41de9fd486197c7285839ea011e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":27,
                  "y":0},
                "size":{
                  "width":202,
                  "height":118}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登陆后",
                      "target":{
                        "targetType":"page",
                        "url":"登陆后.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"92cc0805431e49508ae21e6b43568e7c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1051,
              "y":20},
            "size":{
              "width":80,
              "height":80},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"100"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0629c66df8854813af403c287ac3fea4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1051,
                  "y":20},
                "size":{
                  "width":80,
                  "height":80},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"100"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u4.png"}},
{
          "id":"7b098c52f15a43e8994cda7c7cc75bd7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":0,
              "y":130},
            "size":{
              "width":230,
              "height":890}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3cf93ff92d914c909cacb1842567cbd4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":0,
                  "y":130},
                "size":{
                  "width":230,
                  "height":890}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发布公告页/u6.png"}},
{
          "id":"7e17ee885e074460b8dbc3ab9139de87",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":213},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a7ef57a305e43609758e22f048aac19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":213},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登陆后",
                      "target":{
                        "targetType":"page",
                        "url":"登陆后.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a18cbbfc45f94207a4cc3bc283dbf38d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":308},
            "size":{
              "width":97,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ab9ba917950492abcd07381ca5d6792",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":308},
                "size":{
                  "width":97,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 公告栏主页面",
                      "target":{
                        "targetType":"page",
                        "url":"公告栏主页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0760dff03e0d4faf85e19f91233dabfc",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":400},
            "size":{
              "width":97,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0890017ae7147ee80bdb2024f7357fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":400},
                "size":{
                  "width":97,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 讨论区主页面",
                      "target":{
                        "targetType":"page",
                        "url":"讨论区主页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"622ebe962a8e4ebaa82baf3171e0c0ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":490},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c7ffa52f26a488d9d1dafe9ff1ef9bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":490},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 成绩管理主页面",
                      "target":{
                        "targetType":"page",
                        "url":"成绩管理主页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9eb0b428c7b6447185d997f30277f292",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF363636},
            "location":{
              "x":0,
              "y":1020},
            "size":{
              "width":1200,
              "height":180}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f514dbb569841fbab8918056d5fbb73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF363636},
                "location":{
                  "x":0,
                  "y":1020},
                "size":{
                  "width":1200,
                  "height":180}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u18.png"}},
{
          "id":"635c0750011e401e8e55c1cfec79c9f8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":59,
              "y":1045},
            "size":{
              "width":87,
              "height":85}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e23e9c39ee7944ab8ac71ec397f74b6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":59,
                  "y":1045},
                "size":{
                  "width":87,
                  "height":85}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u20.jpg"}},
{
          "id":"5fe3b635803c466fa55dd2ca61df97b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'方正舒体 Regular', '方正舒体'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":45,
              "y":1140},
            "size":{
              "width":126,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed0fab88578646998979059ba1c1fabb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'方正舒体 Regular', '方正舒体'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":45,
                  "y":1140},
                "size":{
                  "width":126,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d9f9dc6ce26949b48644aefe8a8fa12b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":600,
              "y":1045},
            "size":{
              "width":117,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb662c222ef1474b9f26e40d7eff6bd8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":600,
                  "y":1045},
                "size":{
                  "width":117,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fa1d28e64e7f475e82b63eeaf8779012",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":600,
              "y":1102},
            "size":{
              "width":77,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a6a074e1b634181b78aeac9085a53a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":600,
                  "y":1102},
                "size":{
                  "width":77,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"225d9aa5bb9e4f4c98706773bff7b746",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":693,
              "y":1102},
            "size":{
              "width":77,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ee157c358974c0f991106d72d7788c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":693,
                  "y":1102},
                "size":{
                  "width":77,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"19c94832ef0e4289aadff6d1929cc113",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":600,
              "y":1141},
            "size":{
              "width":77,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bb3155db5c146d7b9ba32d08a7e3f21",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":600,
                  "y":1141},
                "size":{
                  "width":77,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e9ac376e778b4436966cac01fa6d195e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":691,
              "y":1141},
            "size":{
              "width":77,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09eaff4ea9a24c11bd852eec7447d997",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":691,
                  "y":1141},
                "size":{
                  "width":77,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6e5acc92264b45b4be4e0f06303d2b6d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":920,
              "y":1045},
            "size":{
              "width":117,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5144619311941e9b00340a841b0bb63",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":920,
                  "y":1045},
                "size":{
                  "width":117,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"686bc4de82c4467eba1bbe7117698647",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":920,
              "y":1102},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4979f4f1faad48fa8422fe514c05fa67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":920,
                  "y":1102},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u36.png"}},
{
          "id":"145a0bb01916414aa688a8c11c58bb14",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1000,
              "y":1102},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da382902109a4bc2a34422336f8900e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1000,
                  "y":1102},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆后/u36.png"}},
{
          "id":"611cb00b8a714accb673c6b5ab251067",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":1134,
              "y":55},
            "size":{
              "width":24,
              "height":18},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"becca21806644d12aae15030867c77f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":1134,
                  "y":55},
                "size":{
                  "width":24,
                  "height":18},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"切换 set",
                      "objectsToFades":[{
                          "objectPath":["8d2b82ec8cc149e4af21fc4f460bd3fa"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登陆后/u50.png"}},
{
          "id":"8d2b82ec8cc149e4af21fc4f460bd3fa",
          "label":"set",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":false,
          "style":{
            "location":{
              "x":1127,
              "y":87},
            "size":{
              "width":40,
              "height":61},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d630ac64d0314cc49bf7287ebc3ed148",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":40,
                  "height":61}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"35bf1aebc52349779f8015806c27f14a",
                  "label":"设置与退出",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":40,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a3c9f8082aaf4d3aa47804f9a9005e26",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":40,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/登陆后/设置与退出_u54.png"}},
{
                  "id":"d7dd356f811546d2928a143677b38a7e",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":40,
                      "height":31}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6ba73a8b84b24183aa664277d3a6299a",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":30},
                        "size":{
                          "width":40,
                          "height":31}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/登陆后/u56.png"}}]}]},
{
          "id":"e6bedda8e7e64b8584a5ccd075e07cc3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":280,
              "y":180},
            "size":{
              "width":161,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"392dac5ebca047cdbaf79687c2ae1d89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":280,
                  "y":180},
                "size":{
                  "width":161,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dcd844c3f06b4c7790f7beaeaf334462",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":227},
            "size":{
              "width":887,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/发布公告页/u48_line.png"}},
{
          "id":"61eec493d41e4cf9a51daaf2e02475ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":280,
              "y":260},
            "size":{
              "width":49,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"170c374e76ef460c923760e318046640",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":280,
                  "y":260},
                "size":{
                  "width":49,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5d731275f1da444a8881a241ea6bbd54",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":295},
            "size":{
              "width":437,
              "height":37}},
          "adaptiveStyles":{
},
          "placeholderText":"请输入标题"},
{
          "id":"957b3339b88b4e18a7dcd57288f801dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":280,
              "y":380},
            "size":{
              "width":49,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c54fbf1737e42179b055c7553d2dcaf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":280,
                  "y":380},
                "size":{
                  "width":49,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"86a4f1553ed74e8d9d869b564bc55e74",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":415},
            "size":{
              "width":640,
              "height":323}},
          "adaptiveStyles":{
}},
{
          "id":"f2c2d0b006284b36bbe83d965358c563",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":280,
              "y":780},
            "size":{
              "width":640,
              "height":90},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"261b2a40a64d4a278367f8c903e72de1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":280,
                  "y":780},
                "size":{
                  "width":640,
                  "height":90},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发布公告页/u55.png"}},
{
          "id":"558c9f74fd204d5ca3516baa866feb2a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":282,
              "y":782},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00dd61dd9f5a4956b311f4f42572db76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":282,
                  "y":782},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0da60166c5464ace8b36edd9962751eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFF868686},
{
                  "color":0xFF868686}]},
            "location":{
              "x":285,
              "y":823},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0e86f72e48642558f58017bc3b479db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFF868686},
{
                      "color":0xFF868686}]},
                "location":{
                  "x":285,
                  "y":823},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/发布公告页/u59.png"}},
{
          "id":"6f363ed0a5204a0193629e1cfc34d237",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"25px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":282,
              "y":900},
            "size":{
              "width":128,
              "height":60},
            "cornerRadiusTopLeft":"5",
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31bf694d90e54b8ba1cf3f74fea64c21",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"25px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":282,
                  "y":900},
                "size":{
                  "width":128,
                  "height":60},
                "cornerRadiusTopLeft":"5",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/发布公告页/u61.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "8f83df5f3e784aca9ba8bb1b29190670":{
      "scriptId":"u0"},
    "3c19022b82d042f9a5043b07592c1b8b":{
      "scriptId":"u1"},
    "f33f8d0750f3473b8fbc82be66814c15":{
      "scriptId":"u2"},
    "ce5ea41de9fd486197c7285839ea011e":{
      "scriptId":"u3"},
    "92cc0805431e49508ae21e6b43568e7c":{
      "scriptId":"u4"},
    "0629c66df8854813af403c287ac3fea4":{
      "scriptId":"u5"},
    "7b098c52f15a43e8994cda7c7cc75bd7":{
      "scriptId":"u6"},
    "3cf93ff92d914c909cacb1842567cbd4":{
      "scriptId":"u7"},
    "7e17ee885e074460b8dbc3ab9139de87":{
      "scriptId":"u8"},
    "5a7ef57a305e43609758e22f048aac19":{
      "scriptId":"u9"},
    "a18cbbfc45f94207a4cc3bc283dbf38d":{
      "scriptId":"u10"},
    "8ab9ba917950492abcd07381ca5d6792":{
      "scriptId":"u11"},
    "0760dff03e0d4faf85e19f91233dabfc":{
      "scriptId":"u12"},
    "a0890017ae7147ee80bdb2024f7357fe":{
      "scriptId":"u13"},
    "622ebe962a8e4ebaa82baf3171e0c0ec":{
      "scriptId":"u14"},
    "6c7ffa52f26a488d9d1dafe9ff1ef9bc":{
      "scriptId":"u15"},
    "9eb0b428c7b6447185d997f30277f292":{
      "scriptId":"u16"},
    "9f514dbb569841fbab8918056d5fbb73":{
      "scriptId":"u17"},
    "635c0750011e401e8e55c1cfec79c9f8":{
      "scriptId":"u18"},
    "e23e9c39ee7944ab8ac71ec397f74b6e":{
      "scriptId":"u19"},
    "5fe3b635803c466fa55dd2ca61df97b7":{
      "scriptId":"u20"},
    "ed0fab88578646998979059ba1c1fabb":{
      "scriptId":"u21"},
    "d9f9dc6ce26949b48644aefe8a8fa12b":{
      "scriptId":"u22"},
    "bb662c222ef1474b9f26e40d7eff6bd8":{
      "scriptId":"u23"},
    "fa1d28e64e7f475e82b63eeaf8779012":{
      "scriptId":"u24"},
    "9a6a074e1b634181b78aeac9085a53a6":{
      "scriptId":"u25"},
    "225d9aa5bb9e4f4c98706773bff7b746":{
      "scriptId":"u26"},
    "4ee157c358974c0f991106d72d7788c8":{
      "scriptId":"u27"},
    "19c94832ef0e4289aadff6d1929cc113":{
      "scriptId":"u28"},
    "4bb3155db5c146d7b9ba32d08a7e3f21":{
      "scriptId":"u29"},
    "e9ac376e778b4436966cac01fa6d195e":{
      "scriptId":"u30"},
    "09eaff4ea9a24c11bd852eec7447d997":{
      "scriptId":"u31"},
    "6e5acc92264b45b4be4e0f06303d2b6d":{
      "scriptId":"u32"},
    "c5144619311941e9b00340a841b0bb63":{
      "scriptId":"u33"},
    "686bc4de82c4467eba1bbe7117698647":{
      "scriptId":"u34"},
    "4979f4f1faad48fa8422fe514c05fa67":{
      "scriptId":"u35"},
    "145a0bb01916414aa688a8c11c58bb14":{
      "scriptId":"u36"},
    "da382902109a4bc2a34422336f8900e3":{
      "scriptId":"u37"},
    "611cb00b8a714accb673c6b5ab251067":{
      "scriptId":"u38"},
    "becca21806644d12aae15030867c77f3":{
      "scriptId":"u39"},
    "8d2b82ec8cc149e4af21fc4f460bd3fa":{
      "scriptId":"u40"},
    "d630ac64d0314cc49bf7287ebc3ed148":{
      "scriptId":"u41"},
    "35bf1aebc52349779f8015806c27f14a":{
      "scriptId":"u42"},
    "a3c9f8082aaf4d3aa47804f9a9005e26":{
      "scriptId":"u43"},
    "d7dd356f811546d2928a143677b38a7e":{
      "scriptId":"u44"},
    "6ba73a8b84b24183aa664277d3a6299a":{
      "scriptId":"u45"},
    "e6bedda8e7e64b8584a5ccd075e07cc3":{
      "scriptId":"u46"},
    "392dac5ebca047cdbaf79687c2ae1d89":{
      "scriptId":"u47"},
    "dcd844c3f06b4c7790f7beaeaf334462":{
      "scriptId":"u48"},
    "61eec493d41e4cf9a51daaf2e02475ae":{
      "scriptId":"u49"},
    "170c374e76ef460c923760e318046640":{
      "scriptId":"u50"},
    "5d731275f1da444a8881a241ea6bbd54":{
      "scriptId":"u51"},
    "957b3339b88b4e18a7dcd57288f801dd":{
      "scriptId":"u52"},
    "1c54fbf1737e42179b055c7553d2dcaf":{
      "scriptId":"u53"},
    "86a4f1553ed74e8d9d869b564bc55e74":{
      "scriptId":"u54"},
    "f2c2d0b006284b36bbe83d965358c563":{
      "scriptId":"u55"},
    "261b2a40a64d4a278367f8c903e72de1":{
      "scriptId":"u56"},
    "558c9f74fd204d5ca3516baa866feb2a":{
      "scriptId":"u57"},
    "00dd61dd9f5a4956b311f4f42572db76":{
      "scriptId":"u58"},
    "0da60166c5464ace8b36edd9962751eb":{
      "scriptId":"u59"},
    "f0e86f72e48642558f58017bc3b479db":{
      "scriptId":"u60"},
    "6f363ed0a5204a0193629e1cfc34d237":{
      "scriptId":"u61"},
    "31bf694d90e54b8ba1cf3f74fea64c21":{
      "scriptId":"u62"}}});